//! Best-effort Prometheus Pushgateway client, dependency-free (std::net only).
//!
//! Datagen pods are short-to-medium-lived batch jobs; Prometheus pull misses a
//! job that finishes inside a scrape interval, so the pod pushes its metrics to
//! a per-deployment Pushgateway (see docs/design/observability-pushgateway.md).
//! We hand-build the HTTP request over a raw TcpStream rather than pull in a
//! client crate, matching this crate's "no serde, hand-build it" principle
//! (metrics.rs) -- adopting hyper here would make a transitive dep direct.
//!
//! Everything here is best-effort: `metrics.json` (built from the stderr
//! `LB_METRICS_JSON` line) stays the authoritative artifact. A push that fails,
//! times out, or has no gateway configured is silently a no-op and never
//! affects generation. The final push happens after generation completes, so it
//! cannot perturb generated bytes; the periodic reporter only reads shared
//! atomics and does network I/O, never touching the RNG or the data.

use std::fmt::Write as _;
use std::io::Write as _;
use std::net::TcpStream;
use std::time::Duration;

/// Connect + write timeout for a push. Kept short so a slow/dead gateway never
/// stalls the pod; the write path is off the generation hot path regardless.
const PUSH_TIMEOUT: Duration = Duration::from_secs(2);

/// Sets the flag to true on drop -- including during a panic unwind -- so a
/// reporter thread watching the flag always terminates even if the generation
/// body panics. Without this, a panic in the scoped par_iter would never reach
/// the explicit "done" store, the reporter would loop forever, and thread::scope
/// would block joining it (turning a fast-failing generation error, e.g. ENOSPC
/// or an S3 error, into a hung pod).
pub struct StopGuard<'a>(pub &'a std::sync::atomic::AtomicBool);

impl Drop for StopGuard<'_> {
    fn drop(&mut self) {
        self.0.store(true, std::sync::atomic::Ordering::Relaxed);
    }
}

/// The configured Pushgateway base URL, or None when observability is off
/// (env unset/empty). Callers no-op on None.
pub fn gateway_url() -> Option<String> {
    match std::env::var("LB_PUSHGATEWAY_URL") {
        Ok(v) if !v.trim().is_empty() => Some(v.trim().to_string()),
        _ => None,
    }
}

/// The lakebench run id used as a grouping label so a re-run does not read as
/// the previous run's series. Defaults to "unknown" when unset.
pub fn run_id() -> String {
    match std::env::var("LB_RUN_ID") {
        Ok(v) if !v.trim().is_empty() => v.trim().to_string(),
        _ => "unknown".to_string(),
    }
}

/// Split an `http://host:port` (optional trailing path, which is ignored) into
/// (host, port). Returns None if it cannot be parsed. Only http is supported
/// (in-cluster service DNS); https is intentionally unsupported.
pub fn parse_host_port(base_url: &str) -> Option<(String, u16)> {
    let rest = base_url.strip_prefix("http://")?;
    // Drop any path component; we only need host:port to connect.
    let authority = rest.split('/').next().unwrap_or(rest);
    if authority.is_empty() {
        return None;
    }
    match authority.rsplit_once(':') {
        Some((host, port)) => {
            let port: u16 = port.parse().ok()?;
            if host.is_empty() {
                return None;
            }
            Some((host.to_string(), port))
        }
        // No explicit port: default to the pushgateway port.
        None => Some((authority.to_string(), 9091)),
    }
}

/// Append a bare gauge line: `name value\n`.
pub fn gauge(out: &mut String, name: &str, value: f64) {
    // Fixed precision keeps lines compact and stable; non-finite -> 0.
    let v = if value.is_finite() { value } else { 0.0 };
    let _ = writeln!(out, "{} {:.6}", name, v);
}

/// Append a single-label gauge line: `name{label="lval"} value\n`. `lval` is
/// expected to be a simple token (phase name); no escaping is applied.
pub fn gauge_labeled(out: &mut String, name: &str, label: &str, lval: &str, value: f64) {
    let v = if value.is_finite() { value } else { 0.0 };
    let _ = writeln!(out, "{}{{{}=\"{}\"}} {:.6}", name, label, lval, v);
}

/// Build a Pushgateway group path from job + ordered (label, value) pairs:
/// `/metrics/job/<job>/<l1>/<v1>/<l2>/<v2>...`. Values are used as-is; callers
/// pass path-safe tokens (numbers, schema, a lakebench run id).
pub fn group_path(job: &str, labels: &[(&str, &str)]) -> String {
    let mut p = format!("/metrics/job/{}", job);
    for (k, v) in labels {
        let _ = write!(p, "/{}/{}", k, v);
    }
    p
}

/// PUT `body` to `base_url + group_path`, best-effort. Returns Err on any
/// transport failure; callers ignore it. PUT replaces all metrics in the group,
/// so the final authoritative push overwrites any periodic partials.
pub fn push(base_url: &str, group_path: &str, body: &str) -> std::io::Result<()> {
    let (host, port) = parse_host_port(base_url)
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::InvalidInput, "bad url"))?;
    use std::net::ToSocketAddrs;
    let addr = format!("{}:{}", host, port);
    // Resolve + connect with a bounded timeout so a black-holed address cannot
    // hang the caller. Note: DNS resolution itself (to_socket_addrs) is not
    // timeout-bounded; a hung cluster resolver could delay this call. Accepted:
    // the reporter runs on its own thread, and the final push runs only after
    // generation completes and after the authoritative LB_METRICS_JSON line is
    // emitted, so at worst it delays pod exit -- it can never corrupt output or
    // lose the metrics.json source.
    let sock = addr
        .to_socket_addrs()?
        .next()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no addr"))?;
    let mut stream = TcpStream::connect_timeout(&sock, PUSH_TIMEOUT)?;
    stream.set_write_timeout(Some(PUSH_TIMEOUT))?;
    stream.set_read_timeout(Some(PUSH_TIMEOUT))?;
    let req = format!(
        "PUT {path} HTTP/1.1\r\n\
         Host: {host}:{port}\r\n\
         Content-Type: text/plain; version=0.0.4\r\n\
         Content-Length: {len}\r\n\
         Connection: close\r\n\
         \r\n{body}",
        path = group_path,
        host = host,
        port = port,
        len = body.len(),
        body = body,
    );
    stream.write_all(req.as_bytes())?;
    stream.flush()?;
    // We do not need the response; dropping the stream closes it.
    Ok(())
}

/// Periodically push in-progress datagen counters for a live view, until
/// `done` is set. Best-effort; reads only atomics and does network I/O, so it
/// never touches the RNG or generated data and cannot perturb output bytes.
/// Cadence is coarse (~10s); the Prometheus scrape interval bounds granularity
/// anyway. PUT replaces the group, so the final authoritative push (from
/// PodMetrics::emit) overwrites these partials.
#[allow(clippy::too_many_arguments)]
pub fn report_progress(
    url: &str,
    schema: &str,
    node_id: i64,
    run_id: &str,
    rows: &std::sync::atomic::AtomicU64,
    bytes: &std::sync::atomic::AtomicU64,
    start: std::time::Instant,
    done: &std::sync::atomic::AtomicBool,
) {
    use std::sync::atomic::Ordering;
    // A panic in this reporter must NOT unwind the enclosing thread::scope and
    // skip the authoritative emit() that follows it (metrics.json source). Catch
    // it here; on a panic the reporter simply stops.
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let node = node_id.to_string();
        let group = group_path(
            "datagen",
            &[
                ("node_id", node.as_str()),
                ("schema", schema),
                ("run_id", run_id),
            ],
        );
        loop {
            // Sleep ~10s in short slices so `done` is noticed promptly.
            for _ in 0..20 {
                if done.load(Ordering::Relaxed) {
                    return;
                }
                std::thread::sleep(Duration::from_millis(500));
            }
            let r = rows.load(Ordering::Relaxed) as f64;
            let b = bytes.load(Ordering::Relaxed) as f64;
            let el = start.elapsed().as_secs_f64();
            let mut body = String::with_capacity(256);
            gauge(&mut body, "lakebench_datagen_rows_written", r);
            gauge(&mut body, "lakebench_datagen_bytes_written", b);
            gauge(&mut body, "lakebench_datagen_elapsed_seconds", el);
            let mbps = if el > 0.0 { b / el / 1e6 } else { 0.0 };
            gauge(&mut body, "lakebench_datagen_throughput_mbps", mbps);
            let _ = push(url, &group, &body);
        }
    }));
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;
    use std::net::TcpListener;
    use std::thread;

    #[test]
    fn parse_host_port_variants() {
        assert_eq!(
            parse_host_port("http://lakebench-pushgateway.ns.svc:9091"),
            Some(("lakebench-pushgateway.ns.svc".to_string(), 9091))
        );
        // Trailing path is ignored.
        assert_eq!(
            parse_host_port("http://host:1234/metrics/job/x"),
            Some(("host".to_string(), 1234))
        );
        // No port defaults to 9091.
        assert_eq!(
            parse_host_port("http://host"),
            Some(("host".to_string(), 9091))
        );
        // https and garbage are rejected.
        assert_eq!(parse_host_port("https://host:9091"), None);
        assert_eq!(parse_host_port("host:9091"), None);
    }

    #[test]
    fn gauge_lines_format() {
        let mut s = String::new();
        gauge(&mut s, "lakebench_datagen_rows_written", 12345.0);
        gauge_labeled(
            &mut s,
            "lakebench_datagen_phase_seconds",
            "phase",
            "gen",
            1.5,
        );
        assert!(s.contains("lakebench_datagen_rows_written 12345.000000\n"));
        assert!(s.contains("lakebench_datagen_phase_seconds{phase=\"gen\"} 1.500000\n"));
    }

    #[test]
    fn gauge_non_finite_is_zeroed() {
        let mut s = String::new();
        gauge(&mut s, "x", f64::NAN);
        assert!(s.contains("x 0.000000\n"));
    }

    #[test]
    fn group_path_builds_ordered() {
        let p = group_path(
            "datagen",
            &[
                ("node_id", "3"),
                ("schema", "financial"),
                ("run_id", "run-1"),
            ],
        );
        assert_eq!(
            p,
            "/metrics/job/datagen/node_id/3/schema/financial/run_id/run-1"
        );
    }

    #[test]
    fn stop_guard_sets_flag_on_drop() {
        use std::sync::atomic::{AtomicBool, Ordering};
        let flag = AtomicBool::new(false);
        {
            let _g = StopGuard(&flag);
        }
        assert!(flag.load(Ordering::Relaxed));
    }

    #[test]
    fn scoped_reporter_does_not_hang_when_body_panics() {
        // Regression: a panic in the scoped generation body must still let a
        // flag-watching reporter thread terminate, so thread::scope returns
        // instead of blocking forever joining the reporter.
        use std::sync::atomic::{AtomicBool, Ordering};
        use std::time::{Duration, Instant};
        let done = AtomicBool::new(false);
        let started = Instant::now();
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            std::thread::scope(|s| {
                let done_ref = &done;
                s.spawn(move || {
                    // Mimics report_progress: loop until the flag is set.
                    while !done_ref.load(Ordering::Relaxed) {
                        std::thread::sleep(Duration::from_millis(20));
                    }
                });
                let _stop = StopGuard(&done);
                panic!("generation blew up");
            });
        }));
        assert!(
            result.is_err(),
            "the panic should propagate out of the scope"
        );
        assert!(
            done.load(Ordering::Relaxed),
            "the guard must have set the flag"
        );
        assert!(
            started.elapsed() < Duration::from_secs(10),
            "scope must not hang joining the reporter"
        );
    }

    #[test]
    fn gateway_url_none_when_unset() {
        // Not set in the test env -> None (no-op push path).
        std::env::remove_var("LB_PUSHGATEWAY_URL");
        assert!(gateway_url().is_none());
    }

    #[test]
    fn push_sends_put_request_to_a_listener() {
        // A real end-to-end transport test against a throwaway TCP server.
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let handle = thread::spawn(move || {
            let (mut sock, _) = listener.accept().unwrap();
            let mut buf = [0u8; 4096];
            let n = sock.read(&mut buf).unwrap();
            let _ = sock.write_all(b"HTTP/1.1 202 Accepted\r\nContent-Length: 0\r\n\r\n");
            String::from_utf8_lossy(&buf[..n]).to_string()
        });
        let base = format!("http://127.0.0.1:{}", addr.port());
        let path = group_path("datagen", &[("node_id", "0")]);
        push(&base, &path, "lakebench_datagen_rows_written 42.000000\n").unwrap();
        let req = handle.join().unwrap();
        assert!(req.starts_with("PUT /metrics/job/datagen/node_id/0 HTTP/1.1"));
        assert!(req.contains("Content-Type: text/plain"));
        assert!(req.contains("lakebench_datagen_rows_written 42.000000"));
    }
}
