"""What a run record must show to stand as release evidence.

``record_problems`` reads one metrics.json dict and lists every reason it
cannot be cited by the release gate (``scripts/release_gate.py`` checks
``records`` and ``support-record``). An empty list means the record passed,
measured rows in every layer, ran the expected stages and rules, returned
the expected results, was produced by the freeze commit from a clean tree,
read a corpus generated by the release datagen image, and was bound by no
Lakebench limit the release does not allow.

A check whose input another work item still owes fails closed: the record
is refused with a reason naming what is missing, never passed on a guess.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

#: SPEC section 11: (workload, mode, recipe, scale) of every release row.
RELEASE_MATRIX: tuple[tuple[str, str, str, float], ...] = (
    ("customer360", "batch", "hive-iceberg-spark-trino", 1),
    ("customer360", "batch", "polaris-iceberg-spark-trino", 1),
    ("customer360", "batch", "hive-delta-spark-trino", 1),
    ("customer360", "batch", "hive-delta-spark-thrift", 1),
    ("customer360", "batch", "hive-iceberg-spark-thrift", 1),
    ("customer360", "batch", "polaris-iceberg-spark-thrift", 1),
    ("customer360", "batch", "hive-iceberg-spark-duckdb", 1),
    ("customer360", "batch", "polaris-iceberg-spark-duckdb", 1),
    ("customer360", "batch", "hive-iceberg-spark-none", 1),
    ("customer360", "continuous", "hive-iceberg-spark-trino", 1),
    ("customer360", "continuous", "hive-delta-spark-trino", 1),
    ("financial", "batch", "hive-iceberg-spark-trino", 1),
    ("financial", "batch", "polaris-iceberg-spark-trino", 1),
    ("financial", "continuous", "hive-iceberg-spark-trino", 1),
    ("financial", "continuous", "polaris-iceberg-spark-trino", 1),
    ("financial", "batch", "hive-iceberg-spark-trino", 10),
)

#: SPEC section 11's Spark minor and table format version per row, by
#: (workload, mode, recipe). The support record is keyed by them
#: (config/support.py), so a row's runs must use these versions.
_ICEBERG, _SPARK41, _SPARK40 = "1.11.0", "4.1", "4.0"
RELEASE_MATRIX_VERSIONS: dict[tuple[str, str, str], tuple[str, str]] = {
    ("customer360", "batch", "hive-iceberg-spark-trino"): (_SPARK41, _ICEBERG),
    ("customer360", "batch", "polaris-iceberg-spark-trino"): (_SPARK40, _ICEBERG),
    ("customer360", "batch", "hive-delta-spark-trino"): (_SPARK41, "4.1.0"),
    ("customer360", "batch", "hive-delta-spark-thrift"): (_SPARK40, "4.0.0"),
    ("customer360", "batch", "hive-iceberg-spark-thrift"): (_SPARK41, _ICEBERG),
    ("customer360", "batch", "polaris-iceberg-spark-thrift"): (_SPARK40, _ICEBERG),
    ("customer360", "batch", "hive-iceberg-spark-duckdb"): (_SPARK41, _ICEBERG),
    ("customer360", "batch", "polaris-iceberg-spark-duckdb"): (_SPARK40, _ICEBERG),
    ("customer360", "batch", "hive-iceberg-spark-none"): (_SPARK41, _ICEBERG),
    ("customer360", "continuous", "hive-iceberg-spark-trino"): (_SPARK41, _ICEBERG),
    ("customer360", "continuous", "hive-delta-spark-trino"): (_SPARK41, "4.1.0"),
    ("financial", "batch", "hive-iceberg-spark-trino"): (_SPARK41, _ICEBERG),
    ("financial", "batch", "polaris-iceberg-spark-trino"): (_SPARK40, _ICEBERG),
    ("financial", "continuous", "hive-iceberg-spark-trino"): (_SPARK41, _ICEBERG),
    ("financial", "continuous", "polaris-iceberg-spark-trino"): (_SPARK40, _ICEBERG),
}

#: Bound kinds a release row may carry, by (workload, mode, scale). Empty for
#: every row: the matrix runs at scale 1 and 10 with default sizing, and the
#: stored s1 and s10 PASSED records bound nothing. A row that needs a cap
#: gets an entry with its reason, reviewed like the expected-results file.
RELEASE_ALLOWED_BOUNDS: dict[tuple[str, str, float], frozenset[str]] = {}

#: The bound kind an evaluation sizing profile run carries.
EVALUATION_PROFILE_KIND = "evaluation sizing profile"

#: Pipeline stages (experiment.stages.executed, PipelineBenchmark stage
#: names) a release record must have run, by (workload, mode). "query" is
#: the benchmark; a recipe whose query engine is none declares it skipped.
EXPECTED_STAGES: dict[tuple[str, str], tuple[str, ...]] = {
    ("customer360", "batch"): ("bronze", "silver", "gold", "query"),
    ("financial", "batch"): ("bronze", "silver", "gold", "query"),
    ("customer360", "continuous"): ("bronze", "silver", "gold", "query"),
    ("financial", "continuous"): ("bronze", "silver", "gold", "query"),
}
#: The one skip a release record may carry: no benchmark on a recipe with no
#: query engine.
DECLARED_SKIP_NO_ENGINE = "benchmark (skipped: no query engine)"


def _mode(value: Any) -> str:
    """``batch`` or ``continuous`` (config.support.canonical_mode's
    spelling, which the validation record and the verdict use)."""
    return "continuous" if value in ("continuous", "sustained") else str(value)


def _exp(record: Mapping[str, Any]) -> Mapping[str, Any] | None:
    from lakebench.metrics.experiment import experiment_of

    exp = experiment_of(dict(record))
    if not isinstance(exp, Mapping) or exp.get("schema") not in ("exp1", "exp2"):
        return None
    return exp


def record_key(record: Mapping[str, Any]) -> tuple[str, str, str, float] | None:
    """(workload, mode as the matrix spells it, recipe, scale) of a record."""
    exp = _exp(record)
    if exp is None:
        return None
    mode = _mode(exp.get("mode"))
    return (
        str((exp.get("workload") or {}).get("name")),
        mode,
        str((exp.get("architecture") or {}).get("recipe")),
        float((exp.get("corpus") or {}).get("scale") or 0),
    )


# --- the release datagen image ------------------------------------------------


def release_datagen_digest(image: str | None = None) -> str | None:
    """The digest the release datagen image is pinned to: the ``@sha256:``
    part of ``ImagesConfig.datagen``'s default (the look image once it is
    pinned by digest); None while the default is a tag only."""
    if image is None:
        from lakebench.config.schema import ImagesConfig

        image = ImagesConfig().datagen
    if "@" not in image:
        return None
    digest = image.rsplit("@", 1)[1]
    return digest if digest.startswith("sha256:") else None


def _observed_datagen_digest(record: Mapping[str, Any], exp: Mapping[str, Any]) -> str | None:
    dg = ((exp.get("corpus") or {}).get("datagen")) or {}
    if dg.get("digest"):
        return str(dg["digest"])
    if record.get("datagen_fleet"):
        # The fleet saw the pods and named no single digest (several images
        # ran): the series marker cannot vouch for them.
        return None
    obs = ((record.get("config_snapshot") or {}).get("experiment_inputs") or {}).get(
        "corpus_observation"
    ) or {}
    gen = ((obs.get("series") or {}).get("generation")) or {}
    return str(gen["image_digest"]) if gen.get("image_digest") else None


def _image_problems(
    record: Mapping[str, Any], exp: Mapping[str, Any], release_digest: str | None, root: Path | None
) -> list[str]:
    if exp.get("schema") != "exp2":
        return ["exp1 record: release evidence needs corpus id v2 (exp2)"]
    corpus_problems = list((exp.get("corpus") or {}).get("problems") or [])
    if corpus_problems:
        return [f"corpus problems: {'; '.join(map(str, corpus_problems))}"]
    if release_digest is None:
        return ["the release datagen image is not pinned by digest (ImagesConfig.datagen)"]
    observed = _observed_datagen_digest(record, exp)
    if observed != release_digest:
        shown = (observed or "none observed").removeprefix("sha256:")[:12]
        return [f"corpus not generated by the release datagen image ({shown})"]
    from lakebench.metrics.corpus_identity import (
        LineageError,
        check_lineage_evidence,
        load_lineage,
    )

    try:
        table = load_lineage()
    except LineageError as e:
        return [f"the datagen lineage table does not load: {e}"]
    row = table.get(release_digest)
    if row is None:
        return ["the release datagen image has no lineage entry"]
    if root is not None:
        errors = check_lineage_evidence({release_digest: row}, root)
        if errors:
            return [f"the release image's lineage evidence fails: {'; '.join(errors)}"]
    lineage = (exp.get("corpus") or {}).get("lineage")
    if lineage != row.canonical:
        return [f"corpus lineage {lineage} is not the release image's ({row.canonical})"]
    return []


# --- expected results -----------------------------------------------------------


def load_expected(path: Path) -> dict[str, Any]:
    """``uat/expected-results-<version>.json``: ``{"version", "entries":
    [{workload, workload_version, corpus_id_v2, scale, mode: "batch",
    query_set_id, fingerprints: {query: fp}, alert_set?}], "continuous":
    [{workload, workload_version, query_set_ids: [...], fingerprints:
    {query: fp} (customer360, required)}]}``."""
    data = json.loads(path.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("entries"), list):
        raise ValueError(f"{path}: no entries list")
    return data


def round_query_set(rnd: Mapping[str, Any]) -> str | None:
    """The query set an in-stream round counts for in the release record:
    the set it executed (``executed_query_set_id``), or, for a round whose
    only failed queries are the ones the verdict tolerates in every round
    (``verdict.TOLERATED_ROUND_FAILURE_PREFIX``, Q9), the set it listed
    (``query_set_id``). Such a round executed the listed set less Q9, and the
    verdict passed the run with it. It counts for the listed set only when
    the record shows that: the failed queries are listed with ``success``
    false and every one is a Q9, ``executed_queries`` is exactly the listed
    queries less them, and both recorded ids are the ids of those name sets
    (``queries.query_set_id``). A query that was never listed, any other
    failure, or an id that does not match its names leaves the round at the
    set it executed."""
    from lakebench.benchmark.queries import query_set_id
    from lakebench.metrics.verdict import TOLERATED_ROUND_FAILURE_PREFIX

    executed_id = rnd.get("executed_query_set_id")
    listed_id = rnd.get("query_set_id")
    queries = rnd.get("queries")
    executed = rnd.get("executed_queries")
    if not executed_id or not listed_id or listed_id == executed_id:
        return executed_id
    if not isinstance(queries, list) or not isinstance(executed, list):
        return executed_id
    listed: set[str] = set()
    failed: set[str] = set()
    for q in queries:
        if not isinstance(q, Mapping):
            return executed_id
        name = str(q.get("name") or q.get("query_name") or "")
        if not name:
            return executed_id
        listed.add(name)
        if not q.get("success", True):
            failed.add(name)
    if not failed or not all(n.startswith(TOLERATED_ROUND_FAILURE_PREFIX) for n in failed):
        return executed_id
    ran = set(map(str, executed))
    if ran != listed - failed:
        return executed_id
    if query_set_id(listed) != listed_id or query_set_id(ran) != executed_id:
        return executed_id
    return str(listed_id)


def _results_problems(
    record: Mapping[str, Any], exp: Mapping[str, Any], expected: Mapping[str, Any] | None
) -> list[str]:
    if expected is None:
        return ["no expected-results file to check the results against"]
    w = exp.get("workload") or {}
    corpus = exp.get("corpus") or {}
    if _mode(exp.get("mode")) == "continuous":
        entry = next(
            (
                e
                for e in expected.get("continuous") or []
                if e.get("workload") == w.get("name")
                and e.get("workload_version") == w.get("version")
            ),
            None,
        )
        if entry is None:
            return ["no expected query sets for this continuous workload"]
        # The rounds as the pipeline benchmark holds them (where the round
        # recorder writes the executed query set); the top-level copy for a
        # record without them. A round with no QpH (every query failed)
        # executed no set and records none; it is left out, as the
        # composite QpH leaves it out.
        rounds = [
            r
            for r in (
                (record.get("pipeline_benchmark") or {}).get("benchmark_rounds")
                or record.get("benchmark_rounds")
                or []
            )
            if isinstance(r, dict) and isinstance(r.get("qph"), (int, float)) and r["qph"] > 0
        ]
        if not rounds:
            return ["no in-stream round measured a QpH"]
        if any(not r.get("executed_query_set_id") for r in rounds):
            # The declared query_set_id says what a round was asked to run,
            # not what it ran.
            return ["rounds do not record the query set they executed"]
        # A round with a tolerated Q9 failure counts for the set it listed
        # (round_query_set): the verdict passed the run with it.
        ran = {str(round_query_set(r)) for r in rounds}
        want = set(entry.get("query_set_ids") or [])
        if ran != want:
            missing = sorted(want - ran)
            extra = sorted(ran - want)
            return [
                "rounds never ran query set(s) " + ", ".join(missing)
                if missing
                else f"rounds ran unexpected query set(s) {', '.join(extra)}"
            ]
        if w.get("name") == "customer360":
            # C360 continuous: gold read once the corpus settled is compared
            # like a batch result; the entry must list it.
            if not entry.get("fingerprints"):
                return ["no expected fingerprints for this C360 continuous workload"]
            return _fingerprint_problems(exp.get("results") or {}, entry)
        return []
    from lakebench.metrics.alert_set import alert_set_missing

    # An AML batch release row carries its alert set whatever the expected
    # entry holds: a failed fingerprint is never release evidence.
    no_alert_set = alert_set_missing(exp)
    if no_alert_set:
        return [no_alert_set]
    entry = next(
        (
            e
            for e in expected.get("entries") or []
            if e.get("workload") == w.get("name")
            and e.get("workload_version") == w.get("version")
            and e.get("corpus_id_v2") == corpus.get("id_v2")
            and float(e.get("scale") or 0) == float(corpus.get("scale") or 0)
            and _mode(e.get("mode")) == "batch"
        ),
        None,
    )
    if entry is None:
        return ["no expected results for this workload, corpus and scale"]
    if str((exp.get("architecture") or {}).get("recipe") or "").endswith("-none"):
        # No query engine: no results to compare (the stage check holds the
        # declared skip).
        return []
    return _fingerprint_problems(exp.get("results") or {}, entry)


def _fingerprint_problems(results: Mapping[str, Any], entry: Mapping[str, Any]) -> list[str]:
    from lakebench.benchmark.fingerprint import mismatch

    got_fp: dict[str, Any] = dict(results.get("fingerprints") or {})
    want_fp: dict[str, Any] = dict(entry.get("fingerprints") or {})
    problems = []
    if set(got_fp) != set(want_fp):
        problems.append(
            f"queries differ from the expected set (missing {sorted(set(want_fp) - set(got_fp))}, "
            f"extra {sorted(set(got_fp) - set(want_fp))})"
        )
    for query in sorted(set(got_fp) & set(want_fp)):
        why = mismatch(got_fp[query], want_fp[query])
        if why:
            problems.append(f"query {query} result differs from the expected result: {why}")
    if entry.get("alert_set") is not None:
        from lakebench.metrics.alert_set import diff_alert_sets, shape_problem

        alert = results.get("alert_set")
        if alert is None:
            problems.append("no alert-set fingerprint to check against the expected one")
        elif shape_problem(alert) or shape_problem(entry["alert_set"]):
            problems.append(
                "alert set cannot be checked: run "
                f"{shape_problem(alert) or 'well formed'}, expected "
                f"{shape_problem(entry['alert_set']) or 'well formed'}"
            )
        else:
            problems.extend(
                f"{why} (against the expected alert set)"
                for why in diff_alert_sets(alert, entry["alert_set"], "the run", "the expected set")
            )
    return problems


# --- the record -------------------------------------------------------------------


#: The verdict qualifier that lists the layers whose rows were not measured
#: (the layer_rows gate passed on bytes alone). Release evidence must measure
#: rows, so a non-empty list refuses the record. ``verdict_from_record``
#: (the verdict recomputed from the record) sets it with the gate.
LAYER_ROWS_UNMEASURED = "layer_rows_unmeasured"


def _layer_rows_problem(record: Mapping[str, Any]) -> str | None:
    """Rows per layer > 0, from the verdict's ``layer_rows`` gate computed
    from the record, with every layer's rows measured. Fails closed when
    the verdict does not compute that gate or its ``LAYER_ROWS_UNMEASURED``
    qualifier."""
    from lakebench.metrics import verdict as v

    compute = getattr(v, "verdict_from_record", None)
    if compute is None:
        return "rows per layer not checked: the verdict does not compute layer_rows yet"
    verdict = compute(dict(record))
    gate = (getattr(verdict, "gates", None) or {}).get("layer_rows")
    if gate != "PASS":
        return f"rows per layer: layer_rows gate is {gate or 'not computed'}"
    qualifiers = getattr(verdict, "qualifiers", None) or {}
    if LAYER_ROWS_UNMEASURED not in qualifiers:
        return "rows per layer not checked: the verdict does not say which layers were measured"
    unmeasured = list(qualifiers[LAYER_ROWS_UNMEASURED] or [])
    if unmeasured:
        return f"rows not measured for {', '.join(map(str, unmeasured))}"
    return None


def _rules_problems(exp: Mapping[str, Any]) -> list[str]:
    workload = (exp.get("workload") or {}).get("name")
    if workload != "financial":
        return []
    from lakebench.metrics import verdict as v

    rules = exp.get("rules") or {}
    problems = [f"rule {r} errored: {why}" for r, why in (rules.get("errored") or {}).items()]
    allowed = getattr(v, "EXPECTED_SKIPS", None)
    if allowed is None:
        return [*problems, "rule set not checked: the verdict declares no allowed skips yet"]
    from lakebench.benchmark.aml_queries import RULE_TARGETS
    from lakebench.config.support import AML_CONTINUOUS_SKIPPED_RULES

    mode = _mode(exp.get("mode"))
    expected = set(RULE_TARGETS)
    if mode == "continuous":
        expected -= set(AML_CONTINUOUS_SKIPPED_RULES)
    skips = allowed.get((workload, mode), {})
    skipped = rules.get("skipped") or {}
    for rule, why in skipped.items():
        reasons = skips.get(rule, ())
        reasons = {reasons} if isinstance(reasons, str) else set(reasons)
        if str(why) not in reasons:
            problems.append(f"rule {rule} skipped ({why}), not an allowed skip")
    executed = set(rules.get("executed") or [])
    missing = expected - executed - set(skipped)
    if missing:
        problems.append(f"expected rules did not run: {', '.join(sorted(missing))}")
    extra = executed - expected
    if extra:
        problems.append(f"rules outside the expected set ran: {', '.join(sorted(extra))}")
    return problems


def _stage_problems(record: Mapping[str, Any], exp: Mapping[str, Any]) -> list[str]:
    workload = (exp.get("workload") or {}).get("name")
    mode = _mode(exp.get("mode"))
    stages = exp.get("stages") or {}
    executed = set(stages.get("executed") or [])
    skipped = list(stages.get("skipped") or [])
    no_engine = str((exp.get("architecture") or {}).get("recipe") or "").endswith("-none")
    want = set(EXPECTED_STAGES.get((str(workload), mode), ()))
    if no_engine:
        want.discard("query")
    problems = []
    missing = want - executed
    if missing:
        problems.append(f"expected stages did not run: {', '.join(sorted(missing))}")
    allowed = {DECLARED_SKIP_NO_ENGINE} if no_engine else set()
    stray = [s for s in skipped if s not in allowed]
    if stray:
        problems.append(f"stages skipped or failed: {', '.join(stray)}")
    if workload == "financial" and mode == "batch" and not record.get("financial_scoring"):
        problems.append("financial scoring did not run")
    # The C360 continuous result check reads gold once the corpus settled;
    # AML continuous results depend on when the passes ran, so its record
    # says not_checked by design and is held to its query sets instead.
    if mode == "continuous" and workload == "customer360":
        check = (record.get("continuous") or {}).get("result_check") or {}
        fps = check.get("fingerprints") or {}
        failed = [q for q, fp in fps.items() if fp is None] + list(check.get("failed") or [])
        if failed:
            problems.append(
                f"continuous result check queries failed: {', '.join(sorted(set(map(str, failed))))}"
            )
        if check.get("not_checked") or not fps:
            problems.append(
                f"continuous result check did not run: {check.get('not_checked') or 'no result'}"
            )
    return problems


def bound_problems(record: Mapping[str, Any]) -> list[str]:
    """Lakebench limits that make a record's numbers unfit for release or a
    perf baseline: the evaluation sizing profile, or any bound kind the row
    does not allow (``limits.bound_kinds``; never the display list)."""
    exp = _exp(record)
    if exp is None:
        return []
    kinds = list(((exp.get("limits") or {}).get("bound_kinds")) or [])
    key = record_key(record)
    allowed = (
        RELEASE_ALLOWED_BOUNDS.get((key[0], key[1], key[3]), frozenset()) if key else frozenset()
    )
    problems = []
    for kind in kinds:
        if kind == EVALUATION_PROFILE_KIND:
            problems.append("evaluation profile runs are not release evidence")
        elif kind not in allowed:
            problems.append(f"{kind} bound this run; its numbers measure the cap")
    return problems + override_problems(record)


def override_problems(record: Mapping[str, Any]) -> list[str]:
    """Sizing overrides that make a record measure something other than the
    proven profile: an executor count that differs from what the profile asks
    at the run's scale (``limits.executors``; a count below it also binds and
    is labelled, one above it is not, but neither is the proven sizing), or
    any driver override (``architecture.spark_driver_overrides``)."""
    exp = _exp(record)
    if exp is None:
        return []
    problems = []
    for x in (exp.get("limits") or {}).get("executors") or []:
        override = x.get("override")
        if override is None:
            continue
        asks = min(int(x.get("scale_derived") or 0), int(x.get("cap") or 0))
        if int(override) != asks:
            problems.append(
                f"{x.get('job_type')}: executor override {override} "
                f"(profile asks {asks}); not the proven sizing"
            )
    drivers = (exp.get("architecture") or {}).get("spark_driver_overrides") or {}
    if drivers:
        problems.append(
            "driver override "
            + ", ".join(f"{k} {v}" for k, v in sorted(drivers.items()))
            + "; not the proven sizing"
        )
    return problems


def record_problems(
    record: Mapping[str, Any],
    freeze: str | None,
    expected: Mapping[str, Any] | None,
    *,
    release_digest: str | None = None,
    root: Path | None = None,
) -> list[str]:
    """Every reason *record* (a metrics.json dict) cannot be release
    evidence for the freeze commit *freeze*, checked against *expected*
    (``load_expected``). *release_digest* defaults to
    ``release_datagen_digest()``; *root*, the repository, lets the release
    image's lineage evidence file be checked."""
    exp = _exp(record)
    if exp is None:
        return ["no experiment block"]
    from lakebench.aml.look_guard import protected_record_reason
    from lakebench.metrics.verdict import passed

    # A held-out corpus is never release evidence, whether the record
    # declares its role or only carries a seed that hashes to a held-out one.
    # Fail closed: an unreadable held-out record, a withheld or unreadable
    # seed, or a financial record with no corpus seed is refused. Checked
    # first and alone: no other problem is listed for such a record, so no
    # other field (a corpus problem quoting the seed, say) reaches the output.
    # The reason names a role or a kind, never a seed.
    protected = protected_record_reason(record, require_identity=True, fail_closed=True)
    if protected:
        if protected.startswith("unidentified") or "cannot be read" in protected:
            return [f"the corpus is not shown to be outside the held-out AML corpora ({protected})"]
        return [f"the corpus is a protected AML corpus ({protected})"]

    problems: list[str] = []
    kind = record.get("record_kind") or "run"
    if kind != "run":
        problems.append(
            f"a {kind} record (of run {record.get('parent_run_id') or 'unknown'}), not a run"
        )
    if not passed(dict(record)):
        from lakebench.metrics.verdict import stored_passed, verdict_from_record

        reasons = (record.get("verdict") or {}).get("reasons") or record.get("failure_reasons")
        if stored_passed(dict(record)):
            # A stored pass the record no longer shows: name the recomputed reasons.
            try:
                again = verdict_from_record(dict(record)).reasons
            except Exception as e:  # noqa: BLE001 -- the refusal stands; say why
                again = [f"the verdict could not be recomputed ({type(e).__name__}: {e})"]
            reasons = [r for r in again if not r.startswith("Gate '")]
        problems.append(
            "the run did not pass" + (f": {'; '.join(map(str, reasons))}" if reasons else "")
        )
    layer = _layer_rows_problem(record)
    if layer:
        problems.append(layer)
    problems += _stage_problems(record, exp)
    problems += _rules_problems(exp)
    problems += _results_problems(record, exp, expected)
    prov = record.get("provenance") or {}
    if not freeze:
        problems.append("no freeze commit declared")
    elif prov.get("git_sha") != freeze:
        problems.append(
            f"run is not from the freeze commit (ran {str(prov.get('git_sha'))[:12]}, "
            f"freeze {freeze[:12]})"
        )
    if prov.get("git_dirty") is not False:
        problems.append("lakebench ran from a modified tree or one whose state is unknown")
    end = prov.get("end_sample") or {}
    if end.get("code_changed_during_run") is not False:
        problems.append("lakebench code changed during the run, or the run-end sample is missing")
    digest = release_digest if release_digest is not None else release_datagen_digest()
    problems += _image_problems(record, exp, digest, root)
    problems += bound_problems(record)
    if "ml_loop" in record:
        if (exp.get("workload") or {}).get("name") == "financial":
            problems.append("the ML loop is C360 only in v1.7")
        elif not (record["ml_loop"] or {}).get("ml_loop_ok") or not (record.get("run") or {}).get(
            "ml_jobs"
        ):
            problems.append("the ML loop did not complete")
    return problems
