"""The prose guard: no em dash, emoji or AI attribution in a tracked file.

The tracked-tree test is the gate (it runs in every unit leg); the others
plant each kind in a temporary repository. Planted text is built at run
time so this file passes the scan itself.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from tests.conftest import exec_repo_script

ROOT = Path(__file__).resolve().parents[1]
pg = exec_repo_script(ROOT / "scripts/prose_guard.py", "prose_guard")

EM = chr(0x2014)
ROBOT = chr(0x1F916)
TRAILER = "Co-Authored" + "-By: Claude <noreply@example.com>"


def test_tracked_files_are_clean():
    problems = pg.check()
    assert not problems, "prose guard:\n" + "\n".join(problems)


def _repo(tmp_path: Path, files: dict[str, str | bytes]) -> Path:
    git = ["git", "-c", "user.name=t", "-c", "user.email=t@example.com"]
    subprocess.run([*git, "init", "-q"], cwd=tmp_path, check=True)
    for rel, body in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(body, bytes):
            p.write_bytes(body)
        else:
            p.write_text(body, encoding="utf-8")
    subprocess.run([*git, "add", "-A"], cwd=tmp_path, check=True)
    return tmp_path


def _check(repo: Path, allow: str = "") -> list[str]:
    allowlist = repo / "allow.txt"
    allowlist.write_text(allow)
    return pg.check(root=repo, allowlist=allowlist)


def test_added_em_dash_fails_and_names_line(tmp_path):
    repo = _repo(tmp_path, {"docs/a.md": "fine -- text\n"})
    assert _check(repo) == []
    (repo / "docs/a.md").write_text(f"fine -- text\nbad {EM} here\n")
    assert _check(repo) == ["docs/a.md:2 em-dash -- use `--` or restructure"]


@pytest.mark.parametrize(
    ("line", "kind"),
    [
        (f"done {chr(0x2705)}", "emoji"),
        (f"party {chr(0x1F389)}", "emoji"),
        (f"warn {chr(0x26A0)}{chr(0xFE0F)}", "emoji"),
        (f"star {chr(0x2B50)}", "emoji"),
        (TRAILER, "ai-attribution"),
        ("co-authored" + "-by: someone via Anthropic", "ai-attribution"),
        ("Co-Authored" + "-By: GitHub Copilot", "ai-attribution"),
        ("Generated" + " with [Claude Code](https://example.com)", "ai-attribution"),
        (f"{ROBOT} Generated with something", "emoji"),
    ],
)
def test_each_kind_is_reported(tmp_path, line, kind):
    repo = _repo(tmp_path, {"x.py": f"# {line}\n"})
    hits = pg.scan(["x.py"], repo)
    assert kind in {h.kind for h in hits}, hits
    assert all(h.line == 1 for h in hits)


def test_robot_credit_line_is_both_emoji_and_attribution(tmp_path):
    repo = _repo(tmp_path, {"m.txt": f"{ROBOT} generated by a tool\n"})
    assert {h.kind for h in pg.scan(["m.txt"], repo)} == {"emoji", "ai-attribution"}


def test_ordinary_text_is_not_a_hit(tmp_path):
    body = (
        "Co-Authored" + "-By: A Person <a@example.com>\narrows -> => \u2192 and an en dash \u2013\n"
    )
    repo = _repo(tmp_path, {"t.md": body})
    assert pg.scan(["t.md"], repo) == []


def test_binary_and_large_files_are_skipped(tmp_path):
    big = ("x" * 100 + EM + "\n") * (pg.MAX_BYTES // 100 + 1)
    repo = _repo(tmp_path, {"b.bin": b"\0" + EM.encode() + b"\n", "big.txt": big})
    assert pg.scan(["b.bin", "big.txt"], repo) == []


def test_undecodable_file_is_a_hit_not_a_skip(tmp_path):
    repo = _repo(tmp_path, {"l1.txt": b"ok\ncaf\xe9\n"})
    assert pg.scan(["l1.txt"], repo) == [
        pg.Hit("l1.txt", 2, "undecodable", pg.FIXES["undecodable"])
    ]


def test_allowlisted_hit_passes_and_stale_entry_fails(tmp_path):
    repo = _repo(tmp_path, {"g.md": f"golden {EM}\n"})
    assert _check(repo, "g.md:1:em-dash  # a rendered UTF-8 golden\n") == []
    (repo / "g.md").write_text("golden --\n")
    assert _check(repo, "g.md:1:em-dash  # a rendered UTF-8 golden\n") == [
        "allow.txt: stale entry g.md:1:em-dash (no such hit any more; remove it)"
    ]


def test_stale_allowlist_entry_fails(tmp_path):
    repo = _repo(tmp_path, {"a.md": "clean\n"})
    problems = _check(repo, "a.md:1:emoji  # was an emoji\n")
    assert len(problems) == 1 and "stale entry a.md:1:emoji" in problems[0]


@pytest.mark.parametrize(
    "entry", ["a.md:1:em-dash\n", "a.md:x:em-dash  # r\n", "a.md:1:dash  # r\n"]
)
def test_malformed_allowlist_entry_fails(tmp_path, entry):
    repo = _repo(tmp_path, {"a.md": f"x {EM}\n"})
    problems = _check(repo, entry)
    assert any("expected 'path:line:kind  # reason'" in p for p in problems), problems


def test_only_tracked_files_are_scanned(tmp_path):
    repo = _repo(tmp_path, {"a.md": "clean\n"})
    (repo / "untracked.md").write_text(f"x {EM}\n")
    assert _check(repo) == []


def test_tracked_allowlist_is_well_formed():
    entries, bad = pg.load_allowlist()
    assert bad == []
