"""EVD-1: the verdict is decided from the record alone (DESIGN-v1.7 ch03
section 1, ER-3).

Every case starts from a pinned stored record (tests/fixtures/records) and
edits named fields. The six mutations of the acceptance read PASSED before
ER-3 (compute_verdict had no layer, rule, zero-ratio or empty-answer gate)
and FAILED after it, each on its own gate.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from lakebench.metrics import verdict as V
from tests.fixtures import stored_records as sr

ROOT = Path(__file__).resolve().parents[1]
C360_BATCH = "5105a0"  # C360 batch s10, PASSED
AML_BATCH = "1320bd"  # AML batch s1, PASSED, W1 skipped giant-component
AML_CONT = "ebb26f"  # AML continuous s1, PASSED
C360_CONT = "1d17f4"  # C360 continuous s1, PASSED


def _metrics(rec: dict):
    """*rec* loaded the way lakebench loads a stored run."""
    from lakebench.metrics.storage import MetricsStorage

    return MetricsStorage()._dict_to_metrics(rec)


def _job(rec: dict, job_type: str) -> dict:
    return [j for j in rec["jobs"] if j["job_type"] == job_type][-1]


def _stream(rec: dict, job_type: str) -> dict:
    return [s for s in rec["streaming"] if s["job_type"] == job_type][-1]


def _silver_zero(rec: dict) -> None:
    _job(rec, "silver-build")["output_rows"] = 0


def _gold_zero(rec: dict) -> None:
    _job(rec, "gold-finalize")["output_rows"] = 0
    rec["gold_size_gb"] = 0.0


def _answers_empty(rec: dict) -> None:
    for q in rec["benchmark"]["queries"]:
        q["rows_returned"] = 0


def _ratio_zero(rec: dict) -> None:
    # The loader reads the scorecard (scores is its alias); a save writes
    # the same value in all three places.
    pb = rec["pipeline_benchmark"]
    pb["scale_ratio"] = pb["scorecard"]["scale_ratio"] = pb["scores"]["scale_ratio"] = 0.0


def _rules_errored(rec: dict) -> None:
    gold = _job(rec, "gold-finalize")
    gold["rule_errors"] = dict.fromkeys(gold["alerts_by_rule"], "boom")


def _no_alerts(rec: dict) -> None:
    rec["financial_scoring"]["total_alerts"] = 0


MUTATIONS = {
    "silver_rows_0": (C360_BATCH, _silver_zero, "layer_rows"),
    "gold_rows_and_bytes_0": (C360_BATCH, _gold_zero, "layer_rows"),
    "every_answer_empty": (C360_BATCH, _answers_empty, "query_answers"),
    "scale_ratio_0": (C360_BATCH, _ratio_zero, "scale_ratio"),
    "every_rule_errored": (AML_BATCH, _rules_errored, "aml_rules"),
    "zero_alerts": (AML_BATCH, _no_alerts, "aml_rules"),
}


@pytest.mark.parametrize("name", sorted(MUTATIONS))
def test_mutated_records_fail(name: str) -> None:
    """SPEC EVD-1 acceptance: each mutation FAILS on its own gate."""
    run, mutate, gate = MUTATIONS[name]
    rec = sr.load_record(run)
    mutate(rec)
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED", v.reasons
    assert v.gates[gate] == "FAIL"
    assert f"Gate '{gate}' FAILED" in v.reasons
    assert not V.passed(rec)


@pytest.mark.parametrize("run", [C360_BATCH, AML_BATCH, AML_CONT, C360_CONT])
def test_unmutated_records_pass(run: str) -> None:
    rec = sr.load_record(run)
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED", v.reasons
    for gate, outcome in v.gates.items():
        assert outcome == "PASS", gate
    assert v.qualifiers[V.LAYER_ROWS_UNMEASURED] == []
    assert V.passed(rec)


# ---------------------------------------------------------------------------
# The 24 pinned records: the recomputed verdict, from tests/expected
# ---------------------------------------------------------------------------

RECORD_GATES = {"layer_rows", "aml_rules", "scale_ratio", "query_answers"}
EXPECTED = json.loads((ROOT / "tests" / "expected" / "verdict_recomputed.json").read_text())


@pytest.mark.parametrize("run", sorted(EXPECTED["records"]))
def test_pinned_records_recompute_as_expected(run: str) -> None:
    """Every pinned record's verdict from the record alone, and the gates
    that fail it. A stored pass that reads failed here is listed in
    UPGRADING; the expected file is never regenerated by code."""
    want = EXPECTED["records"][run]
    rec = sr.load_record(run)
    v = V.verdict_from_record(rec)
    assert v.status == want["status"], v.reasons
    failing = sorted(g for g, o in v.gates.items() if o == "FAIL" and g in RECORD_GATES)
    assert failing == want["failing_gates"]
    assert v.qualifiers.get(V.LAYER_ROWS_UNMEASURED) == want["layer_rows_unmeasured"]
    assert V.passed(rec) is (want["status"] == "PASSED")


def test_only_the_listed_stored_passes_flip() -> None:
    """A stored pass (PASSED, or success on a record with no verdict block)
    that recomputes as failed is one of the three listed records."""
    flips = []
    for run in sr.record_ids():
        rec = sr.load_record(run)
        if V.stored_passed(rec) and not V.passed(rec):
            flips.append(run)
    assert flips == sorted(EXPECTED["stored_pass_now_failed"])


# ---------------------------------------------------------------------------
# c360, W1 skips, continuous rules, dependency set
# ---------------------------------------------------------------------------


def test_c360_non_gating_failure_is_a_qualifier() -> None:
    """A failed check outside GATING_CHECKS is recorded in the qualifier
    CD-14 defined, never a FAIL (and not a badge warning: the carry is the
    qualifier, which the report renders)."""
    rec = sr.load_record(C360_BATCH)
    check = next(c for c in rec["c360_correctness"]["checks"] if c["id"] == "interaction_mix")
    check["status"] = "fail"
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    assert v.qualifiers["c360_failed_not_gating"] == ["interaction_mix"]


def test_c360_gated_failure_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    check = next(c for c in rec["c360_correctness"]["checks"] if c["id"] == "silver_to_gold_days")
    check["status"] = "fail"
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["c360"] == "FAIL"


def test_w1_giant_component_skip_passes() -> None:
    rec = sr.load_record(AML_BATCH)
    assert V.verdict_from_record(rec).gates["aml_rules"] == "PASS"
    _job(rec, "gold-finalize")["rules_skipped"]["W1_connected_components"] = "timeout"
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"
    assert any("W1_connected_components skipped (timeout)" in r for r in v.reasons)


def test_w1_vertex_cap_skip_passes() -> None:
    rec = sr.load_record(AML_BATCH)
    _job(rec, "gold-finalize")["rules_skipped"]["W1_connected_components"] = "vertex-cap"
    assert V.verdict_from_record(rec).status == "PASSED"


def test_expected_rule_missing_fails() -> None:
    """A rule that neither ran nor was skipped (left out of the job's
    per-rule counts) fails: nothing was silently skipped."""
    rec = sr.load_record(AML_BATCH)
    del _job(rec, "gold-finalize")["alerts_by_rule"]["W6_pep_counterparty"]
    v = V.verdict_from_record(rec)
    assert v.gates["aml_rules"] == "FAIL"
    assert any("expected rules did not run: W6_pep_counterparty" in r for r in v.reasons)


def test_no_per_rule_counts_is_a_warning_not_a_fail() -> None:
    """With no per-rule counts in the gold log the rule set is not
    measured: the CLI warns, and so does the verdict."""
    rec = sr.load_record(AML_BATCH)
    _job(rec, "gold-finalize")["alerts_by_rule"] = {}
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert any("executed rule set not recorded" in w for w in warnings)


def test_continuous_mode_excluded_rule_ran_fails() -> None:
    rec = sr.load_record(AML_CONT)
    gold = _stream(rec, "gold-refresh")
    gold["ttd_by_rule"]["W1_connected_components"] = {"alerts": 3}
    rec["experiment"]["rules"]["executed"].append("W1_connected_components")
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"
    assert any("W1_connected_components" in r for r in v.reasons)


def test_continuous_rule_with_no_alerts_is_not_a_fail() -> None:
    """Continuous knows a rule ran only from its time-to-detect lines, which
    a rule with no alerts does not write."""
    rec = sr.load_record(AML_CONT)
    del _stream(rec, "gold-refresh")["ttd_by_rule"]["W3_round_tripping"]
    assert V.verdict_from_record(rec).status == "PASSED"


def test_pod_set_mismatch_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["provenance"]["deps"] = {"pod_mismatches": [{"pod": "x", "pinset": "a" * 64}]}
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["dependency_set"] == "FAIL"
    del rec["provenance"]["deps"]
    assert "dependency_set" not in V.verdict_from_record(rec).gates


def test_ml_jobs_not_counted() -> None:
    """Only jobs[] carries pipeline layers; a model-training job record
    elsewhere in the record is never counted as a layer."""
    rec = sr.load_record(C360_BATCH)
    rec["ml_jobs"] = [{"job_type": "gold-finalize", "output_rows": 0, "success": True}]
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED" and v.gates["layer_rows"] == "PASS"


# ---------------------------------------------------------------------------
# Layers: continuous sources, bytes fallback, run --stage, failed stages
# ---------------------------------------------------------------------------


def test_aml_continuous_gold_is_measured_by_its_alerts() -> None:
    rec = sr.load_record(AML_CONT)
    assert _stream(rec, "gold-refresh")["output_rows"] is None
    assert V.verdict_from_record(rec).qualifiers[V.LAYER_ROWS_UNMEASURED] == []
    _stream(rec, "gold-refresh")["ttd_alerts"] = None
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    assert v.qualifiers[V.LAYER_ROWS_UNMEASURED] == ["gold"]
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert "rows not measured for gold; bytes > 0" in warnings
    rec["gold_size_gb"] = 0.0
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["layer_rows"] == "FAIL"


def test_continuous_silver_rows_written_zero_fails() -> None:
    """Silver's rows after the transforms are what it wrote; rows read and
    committed do not show a non-empty silver."""
    rec = sr.load_record(C360_CONT)
    assert _stream(rec, "silver-stream")["committed_rows"] > 0
    _stream(rec, "silver-stream")["output_rows"] = 0
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["layer_rows"] == "FAIL"


def test_aml_continuous_silver_falls_back_to_committed_rows() -> None:
    """The AML silver stream logs no rows after transforms: its committed
    batches' rows stand for them, and 0 fails."""
    rec = sr.load_record(AML_CONT)
    assert _stream(rec, "silver-stream")["output_rows"] is None
    _stream(rec, "silver-stream")["committed_rows"] = 0
    assert V.verdict_from_record(rec).gates["layer_rows"] == "FAIL"


def test_aml_continuous_zero_alerts_fails() -> None:
    rec = sr.load_record(AML_CONT)
    gold = _stream(rec, "gold-refresh")
    gold["ttd_alerts"], gold["ttd_unmatched"], gold["ttd_by_rule"] = 0, 0, {}
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED"
    assert v.gates["layer_rows"] == "FAIL" and v.gates["aml_rules"] == "FAIL"
    assert any("zero alerts" in r for r in v.reasons)


def test_aml_continuous_unmatched_alerts_count() -> None:
    rec = sr.load_record(AML_CONT)
    gold = _stream(rec, "gold-refresh")
    gold["ttd_alerts"], gold["ttd_unmatched"] = 0, 12
    assert V.verdict_from_record(rec).status == "PASSED"


def test_aml_continuous_zero_with_an_unmeasured_cycle_is_not_counted() -> None:
    """No alerts counted while a cycle could not count them proves nothing:
    gold falls back to its bytes."""
    rec = sr.load_record(AML_CONT)
    gold = _stream(rec, "gold-refresh")
    gold["ttd_alerts"], gold["ttd_unmatched"], gold["ttd_unmeasured_cycles"] = 0, 0, 2
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    assert v.qualifiers[V.LAYER_ROWS_UNMEASURED] == ["gold"]


def test_batch_missing_stage_job_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] != "gold-finalize"]
    v = V.verdict_from_record(rec)
    assert v.gates["layer_rows"] == "FAIL"
    assert any("no gold-finalize job recorded" in r for r in v.reasons)


def test_stage_only_record_judges_its_layer() -> None:
    """``run --stage silver-build`` runs one stage: the other layers are not
    the run's, and its ratio of 0 is not a missing measurement."""
    rec = sr.load_record(C360_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] == "silver-build"]
    _ratio_zero(rec)
    assert V.verdict_from_record(rec).status == "FAILED"
    rec["stage_only"] = "silver-build"
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED", v.reasons
    _silver_zero(rec)
    assert V.verdict_from_record(rec).gates["layer_rows"] == "FAIL"


def test_failed_stage_adds_no_record_gate() -> None:
    """A failed stage fails the run; the empty layers after it are its
    consequence and add no gate."""
    rec = sr.load_record(C360_BATCH)
    _job(rec, "silver-build")["success"] = False
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] != "gold-finalize"]
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["pipeline"] == "FAIL"
    assert "layer_rows" not in v.gates


def test_interrupted_record_stays_interrupted() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["success"] = False
    rec["interrupted"] = {
        "signal": "SIGINT",
        "at_stage": "gold-finalize",
        "at_utc": "2026-09-29T21:30:00+00:00",
        "prior_failure": False,
    }
    gold = _job(rec, "gold-finalize")
    gold["success"], gold["error_message"], gold["output_rows"] = False, "interrupted", 0
    v = V.verdict_from_record(rec)
    assert v.status == "INTERRUPTED", v.reasons
    assert "layer_rows" not in v.gates


def test_unknown_query_name_is_a_warning() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["benchmark"]["queries"][0].update(name="Q99_renamed", rows_returned=0)
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert any("Q99_renamed" in w for w in warnings)


def test_allow_empty_query_may_return_no_rows() -> None:
    from lakebench.benchmark.queries import BENCHMARK_QUERIES_BY_DOMAIN

    allowed = next(
        q.name for qs in BENCHMARK_QUERIES_BY_DOMAIN.values() for q in qs if q.allow_empty
    )
    rec = sr.load_record(C360_BATCH)
    rec["benchmark"]["queries"][0].update(name=allowed, rows_returned=0)
    assert V.verdict_from_record(rec).gates["query_answers"] == "PASS"


def test_unmeasured_answer_is_not_judged() -> None:
    rec = sr.load_record(C360_BATCH)
    for q in rec["benchmark"]["queries"]:
        q.pop("rows_returned")
    assert V.verdict_from_record(rec).status == "PASSED"


# ---------------------------------------------------------------------------
# Readers: passed() never promotes and recomputes a stored pass
# ---------------------------------------------------------------------------


def test_passed_never_promotes() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["verdict"]["status"] = "FAILED"
    assert V.verdict_from_record(rec).status == "PASSED"
    assert V.passed(rec) is False


def test_passed_recomputes_a_stored_pass() -> None:
    rec = sr.load_record(C360_BATCH)
    assert rec["verdict"]["status"] == "PASSED"
    _silver_zero(rec)
    assert V.stored_passed(rec) is True
    assert V.passed(rec) is False


def test_summary_row_is_judged_on_what_it_stored() -> None:
    """A list_runs row has no jobs list: nothing to recompute from."""
    assert V.passed({"run_id": "r", "success": True, "verdict_status": "PASSED"}) is True
    assert V.passed({"run_id": "r", "success": False}) is False


def test_unreadable_record_reads_not_passed() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["start_time"] = "not a time"
    assert V.passed(rec) is False


def test_fresh_record_reads_back_its_saved_verdict() -> None:
    """The verdict a save writes is the one a reader recomputes."""
    m = sr.load_metrics(C360_BATCH)
    saved = m.to_dict()
    assert V.verdict_from_record(saved).to_dict() == saved["verdict"]
    _job_obj = [j for j in m.jobs if j.job_type == "silver-build"][-1]
    _job_obj.output_rows = 0
    saved = m.to_dict()
    assert saved["verdict"]["status"] == "FAILED"
    assert V.verdict_from_record(saved).to_dict() == saved["verdict"]


# ---------------------------------------------------------------------------
# The CLI's save gate (cli/_run.py, cli/_sustained.py)
# ---------------------------------------------------------------------------


def test_save_gate_fails_a_run_the_record_fails() -> None:
    m = sr.load_metrics(C360_BATCH)
    [j for j in m.jobs if j.job_type == "gold-finalize"][-1].output_rows = 0
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is False
    assert m.success is False
    assert any("gold has 0 rows" in s for s in said)
    assert any("gold has 0 rows" in r for r in m.failure_reasons)
    v = m.to_dict()["verdict"]
    assert v["status"] == "FAILED"
    assert any("gold has 0 rows" in r for r in v["reasons"])
    assert v["gates"]["layer_rows"] == "FAIL"


def test_save_gate_keeps_a_passing_run() -> None:
    m = sr.load_metrics(C360_BATCH)
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is True
    assert m.success is True and said == [] and m.failure_reasons == []


def test_save_gate_leaves_a_failed_run_alone() -> None:
    m = sr.load_metrics(C360_BATCH)
    said: list[str] = []
    assert V.apply_save_gate(m, False, said.append) is False
    assert said == []


def test_save_gate_fails_closed_when_the_record_cannot_be_judged(monkeypatch) -> None:
    m = sr.load_metrics(C360_BATCH)

    def boom(record):
        raise RuntimeError("bad record")

    monkeypatch.setattr(V, "_recompute", boom)
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is False
    assert any("could not be computed" in s for s in said)


@pytest.mark.parametrize("path", ["src/lakebench/cli/_run.py", "src/lakebench/cli/_sustained.py"])
def test_every_cli_save_follows_the_save_gate(path: str) -> None:
    """Each save of a run record is preceded by the save gate, after the
    last late-signal check before it (an interrupt still reads INTERRUPTED),
    with only writers between them that the verdict does not read: the end
    samples, the corpus observation and the series seal."""
    src = (ROOT / path).read_text()
    saves = [
        i for i in range(len(src)) if src.startswith("metrics_storage.save_run(run_metrics)", i)
    ]
    assert saves
    for i in saves:
        gate = src.rfind("apply_save_gate(run_metrics", 0, i)
        assert gate != -1 and i - gate < 2000, "no save gate before the save"
        assert src.rfind("late_signal()", 0, i) < gate, "the late-signal check must come first"
        between = src[gate:i]
        assert "save_run(" not in between and "late_signal()" not in between
        assert ".success = True" not in between


# ---------------------------------------------------------------------------
# The release gate reads the real verdict (ER-16's fail-closed inputs)
# ---------------------------------------------------------------------------


def test_release_record_reads_layer_rows_and_expected_skips() -> None:
    from lakebench.metrics import release_record as rr

    assert rr.LAYER_ROWS_UNMEASURED == V.LAYER_ROWS_UNMEASURED
    assert rr._layer_rows_problem(sr.load_record(C360_BATCH)) is None
    assert rr._rules_problems(sr.load_record(AML_BATCH)["experiment"]) == []
    rec = sr.load_record(AML_CONT)
    _stream(rec, "gold-refresh")["ttd_alerts"] = None
    assert rr._layer_rows_problem(rec) == "rows not measured for gold"
    bad = copy.deepcopy(sr.load_record(C360_BATCH))
    _silver_zero(bad)
    assert rr._layer_rows_problem(bad) == "rows per layer: layer_rows gate is FAIL"


# ---------------------------------------------------------------------------
# Through the real run(): the QA-9 harness, one layer emptied after parsing
# ---------------------------------------------------------------------------


def _saved_record(tmp_path: Path) -> dict:
    (path,) = tmp_path.glob("lakebench-output/runs/run-*/metrics.json")
    return json.loads(path.read_text())


def test_batch_run_with_empty_gold_exits_non_zero(tmp_path, monkeypatch) -> None:
    """Every stage succeeds and the CLI's own gates pass, but gold-finalize
    wrote no rows: the run exits 1 and its record reads FAILED on
    layer_rows. Before ER-3 it exited 0 with a PASSED record."""
    from lakebench.metrics.collector import MetricsCollector
    from tests.harness.run_harness import SCENARIOS, invoke_scenario

    real = MetricsCollector.parse_driver_logs

    def gold_empty(self, logs, job_type):
        m = real(self, logs, job_type)
        if job_type == "gold-finalize":
            m.output_rows = 0
        return m

    monkeypatch.setattr(MetricsCollector, "parse_driver_logs", gold_empty)
    result, _rec = invoke_scenario(SCENARIOS["batch_c360"], tmp_path, monkeypatch)
    assert result.exit_code == 1, result.output
    assert "Verdict: gold has 0 rows" in result.output
    saved = _saved_record(tmp_path)
    assert saved["success"] is False
    assert saved["verdict"]["status"] == "FAILED"
    assert saved["verdict"]["gates"]["layer_rows"] == "FAIL"
    assert V.passed(saved) is False


def test_continuous_run_with_empty_gold_exits_non_zero(tmp_path, monkeypatch) -> None:
    """The continuous path: gold-refresh wrote no rows in the window, which
    the CLI's continuous gate (bronze and silver rows) does not check."""
    from lakebench.metrics.collector import StreamingJobMetrics
    from tests.harness.run_harness import SCENARIOS, invoke_scenario

    real = StreamingJobMetrics.apply_window

    def gold_empty(self, logs, start, end):
        stats = real(self, logs, start, end)
        if self.job_type == "gold-refresh":
            self.output_rows = 0
        return stats

    monkeypatch.setattr(StreamingJobMetrics, "apply_window", gold_empty)
    result, _rec = invoke_scenario(SCENARIOS["continuous_c360"], tmp_path, monkeypatch)
    assert result.exit_code == 1, result.output
    assert "Verdict: gold has 0 rows" in result.output
    saved = _saved_record(tmp_path)
    assert saved["success"] is False
    assert saved["verdict"]["status"] == "FAILED"
    assert saved["verdict"]["gates"]["layer_rows"] == "FAIL"


# ---------------------------------------------------------------------------
# Review fixes: single stages, continuous rounds, fallbacks, cycles, rounding
# ---------------------------------------------------------------------------


def test_stage_gold_finalize_judges_the_rules() -> None:
    """``run --stage gold-finalize`` runs detection: its rules are judged."""
    rec = sr.load_record(AML_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] == "gold-finalize"]
    rec["stage_only"] = "gold-finalize"
    assert V.verdict_from_record(rec).status == "PASSED"
    _rules_errored(rec)
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"


def test_stage_other_than_bronze_has_no_scale_ratio() -> None:
    """A single later stage divides another layer's input by the expected
    bronze: not a scale measurement."""
    rec = sr.load_record(AML_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] == "gold-finalize"]
    rec["stage_only"] = "gold-finalize"
    pb = rec["pipeline_benchmark"]
    pb["scale_ratio"] = pb["scorecard"]["scale_ratio"] = pb["scores"]["scale_ratio"] = 0.393
    v = V.verdict_from_record(rec)
    assert "scale_ratio" not in v.gates and v.status == "PASSED"
    rec["stage_only"] = "bronze-verify"
    rec["jobs"] = [j for j in sr.load_record(AML_BATCH)["jobs"] if j["job_type"] == "bronze-verify"]
    assert V.verdict_from_record(rec).gates["scale_ratio"] == "FAIL"


def _round_query(rec: dict, idx: int, name: str) -> dict:
    return next(q for q in rec["benchmark_rounds"][idx]["queries"] if q["name"] == name)


def test_continuous_early_round_may_be_empty() -> None:
    """Only the last in-stream round is held to the empty-answer rule, as
    the CLI holds it; the aggregate keeps round 1's rows."""
    rec = sr.load_record(C360_CONT)
    _round_query(rec, 0, "Q1_full_aggregation_scan")["rows_returned"] = 0
    rec["benchmark"]["queries"][0]["rows_returned"] = 0
    assert V.verdict_from_record(rec).status == "PASSED"
    _round_query(rec, -1, "Q1_full_aggregation_scan")["rows_returned"] = 0
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["query_answers"] == "FAIL"


def test_continuous_q9_failure_is_tolerated_other_failures_are_not() -> None:
    rec = sr.load_record(C360_CONT)
    _round_query(rec, 0, "Q9_executive_dashboard")["success"] = False
    next(q for q in rec["benchmark"]["queries"] if q["name"].startswith("Q9"))["success"] = False
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED" and v.gates["benchmark"] == "PASS"
    _round_query(rec, 2, "Q2_filtered_aggregation")["success"] = False
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["benchmark"] == "FAIL"


def test_zero_alerts_without_scoring_fails_on_the_rule_counts() -> None:
    rec = sr.load_record(AML_BATCH)
    del rec["financial_scoring"]
    assert V.verdict_from_record(rec).gates["aml_rules"] == "PASS"
    gold = _job(rec, "gold-finalize")
    gold["alerts_by_rule"] = dict.fromkeys(gold["alerts_by_rule"], 0)
    v = V.verdict_from_record(rec)
    assert v.gates["aml_rules"] == "FAIL"
    assert any("zero alerts (every rule 0)" in r for r in v.reasons)


def test_query_benchmark_fallback_is_judged() -> None:
    """A record whose answers are only in the pipeline benchmark."""
    rec = sr.load_record(C360_BATCH)
    del rec["benchmark"]
    for q in rec["pipeline_benchmark"]["query_benchmark"]["queries"]:
        q["rows_returned"] = 0
    v = V.verdict_from_record(rec)
    assert v.gates["query_answers"] == "FAIL"


def test_multi_cycle_reads_the_last_job_of_each_layer() -> None:
    rec = sr.load_record(C360_BATCH)
    first = copy.deepcopy(_job(rec, "silver-build"))
    first["output_rows"] = 0
    rec["jobs"].insert(1, first)  # an earlier cycle with 0 rows, the last has rows
    assert V.verdict_from_record(rec).gates["layer_rows"] == "PASS"
    rec["jobs"][1]["output_rows"], _job(rec, "silver-build")["output_rows"] = 5, 0
    assert V.verdict_from_record(rec).gates["layer_rows"] == "FAIL"


def test_multi_cycle_scale_ratio_reads_the_last_bronze_stage() -> None:
    """Each cycle's bronze-verify reads every cycle so far; the scale ratio
    is the last one's (the first read cycle 1 only)."""
    from lakebench.metrics.collector import JobMetrics, build_pipeline_benchmark

    m = sr.load_metrics(C360_BATCH)
    full = m.pipeline_benchmark.scale_ratio
    bronze = [j for j in m.jobs if j.job_type == "bronze-verify"][-1]
    cycle1 = JobMetrics(**{**bronze.__dict__, "input_size_gb": bronze.input_size_gb / 2})
    m.jobs.insert(0, cycle1)
    pb = build_pipeline_benchmark(m)
    assert pb.scale_ratio == pytest.approx(full, rel=1e-3)


def test_stored_verdict_is_the_recomputed_one_at_a_rounding_edge() -> None:
    """A scale ratio of 0.9496 is stored as 0.949, never rounded up to the
    0.95 it fails against: the stored verdict, the save gate and every
    reader judge the stored value, and it fails as the measurement does."""
    m = sr.load_metrics(C360_BATCH)
    m.pipeline_benchmark.scale_ratio = 0.9496
    saved = m.to_dict()
    assert saved["pipeline_benchmark"]["scale_ratio"] == 0.949
    assert saved["verdict"]["status"] == "FAILED"
    assert V.verdict_from_record(saved).to_dict() == saved["verdict"]
    assert V.save_gate_problems(m)
    m.pipeline_benchmark.scale_ratio = 0.95004
    saved = m.to_dict()
    assert saved["pipeline_benchmark"]["scale_ratio"] == 0.95
    assert saved["verdict"]["status"] == "PASSED"
    assert V.save_gate_problems(m) == []


def test_ratio_out_rounds_as_before_away_from_the_threshold() -> None:
    from lakebench.metrics.collector import ratio_out

    assert ratio_out(1.00888, 3) == 1.009
    assert ratio_out(0.99149, 3) == 0.991
    assert ratio_out(0.9496, 3) == 0.949
    assert ratio_out(0.94996, 4) == 0.9499
    assert ratio_out(0.5, 3) == 0.5


def test_save_gate_reason_comes_first() -> None:
    """A run the save gate fails reads its own reason first, not a crash."""
    m = sr.load_metrics(C360_BATCH)
    [j for j in m.jobs if j.job_type == "gold-finalize"][-1].output_rows = 0
    V.apply_save_gate(m, True, lambda _line: None)
    reasons = m.to_dict()["verdict"]["reasons"]
    assert reasons[0].startswith("gold has 0 rows")
    assert "Pipeline crashed or was interrupted" not in reasons


def test_summary_rows_carry_the_recomputed_pass(tmp_path: Path) -> None:
    """``report --list`` reads summary rows: a stored success the record no
    longer shows lists as failed."""
    from lakebench.metrics.storage import MetricsStorage

    for run in ("497f02", C360_BATCH):
        rec = sr.load_record(run)
        d = tmp_path / f"run-{rec['run_id']}"
        d.mkdir()
        (d / "metrics.json").write_text(json.dumps(rec))
    rows = {r["run_id"][-6:]: r for r in MetricsStorage(tmp_path).list_runs()}
    assert rows["497f02"]["passed"] is False and rows["497f02"]["success"] is True
    assert rows[C360_BATCH]["passed"] is True


def test_local_run_exits_one_when_its_record_fails(tmp_path, monkeypatch) -> None:
    """``run --local`` through the real save: every stage succeeds, gold
    wrote no rows, the record reads FAILED and the run exits 1."""
    from types import SimpleNamespace

    from typer.testing import CliRunner

    import lakebench.cli._local as local
    import lakebench.cli._run as run_mod
    from lakebench.cli import app
    from lakebench.metrics import JobMetrics

    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("LAKEBENCH_S3_ACCESS_KEY", "test-access")
    monkeypatch.setenv("LAKEBENCH_S3_SECRET_KEY", "test-secret")
    stages = [
        ("bronze-verify", True, 1.0),
        ("silver-build", True, 1.0),
        ("gold-finalize", True, 1.0),
    ]
    monkeypatch.setattr(local, "check_local_supported", lambda *a, **k: None)
    monkeypatch.setattr(local, "deploy_local", lambda *a, **k: SimpleNamespace())
    monkeypatch.setattr(
        local,
        "run_local",
        lambda *a, **k: SimpleNamespace(success=True, stages=stages, elapsed_seconds=3.0, logs={}),
    )
    monkeypatch.setattr(local, "print_local_summary", lambda *a, **k: None)

    def jobs(collector, cfg, result):
        for name, _ok, _e in result.stages:
            rows = 0 if name == "gold-finalize" else 100
            collector.record_job(
                JobMetrics(
                    job_name=f"lakebench-{name}", job_type=name, success=True, output_rows=rows
                )
            )

    monkeypatch.setattr(run_mod, "_record_local_jobs", jobs)

    class NoS3:
        def __init__(self, *a, **k):
            raise RuntimeError("no local store in this test")

    monkeypatch.setattr("lakebench.s3.S3Client", NoS3)
    monkeypatch.setattr(run_mod, "_load_latest_datagen_fleet", lambda *a, **k: None)
    monkeypatch.setattr(run_mod, "write_run_report", lambda *a, **k: None)
    cfg = tmp_path / "c.yaml"
    init = CliRunner().invoke(app, ["init", "--output", str(cfg), "--scale", "1"])
    assert init.exit_code == 0, init.output
    result = CliRunner().invoke(app, ["run", str(cfg), "--local", "--skip-benchmark", "--yes"])
    assert result.exit_code == 1, result.output
    assert "Verdict: gold has 0 rows" in result.output
    saved = _saved_record(tmp_path)
    assert saved["success"] is False and saved["verdict"]["gates"]["layer_rows"] == "FAIL"


# ---------------------------------------------------------------------------
# path-cap (owner, 10-03): an allowed, labelled Lakebench cap for W3 and W17
# ---------------------------------------------------------------------------


def _s100_without_its_benchmark_failure() -> dict:
    """The stored s100 AML batch record (W1 vertex-cap, W3 and W17 path-cap)
    with the two fields of its unrelated benchmark failure edited out: the
    ImportError (benchmark_error) and the success flag it cleared."""
    rec = sr.load_record("85b404")
    del rec["benchmark_error"]
    rec["success"] = True
    return rec


def test_s100_path_cap_skips_pass_with_the_cap_qualifier() -> None:
    rec = _s100_without_its_benchmark_failure()
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED", v.reasons
    assert v.gates["aml_rules"] == "PASS"
    assert v.qualifiers[V.RULE_CAPS] == {
        "W17_layering_chain": "path-cap",
        "W1_connected_components": "vertex-cap",
        "W3_round_tripping": "path-cap",
    }
    # The same skips are labelled as Lakebench bounds in the stored limits.
    kinds = rec["experiment"]["limits"]["bound_kinds"]
    assert "rule W3_round_tripping cap" in kinds and "rule W17_layering_chain cap" in kinds


def test_s100_other_skip_still_fails() -> None:
    rec = _s100_without_its_benchmark_failure()
    gold = _job(rec, "gold-finalize")
    gold["rules_skipped"]["W3_round_tripping"] = "timeout"
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"
    assert any("W3_round_tripping skipped (timeout)" in r for r in v.reasons)
    rec = _s100_without_its_benchmark_failure()
    _job(rec, "gold-finalize")["rules_skipped"]["W2_structuring"] = "path-cap"
    assert V.verdict_from_record(rec).gates["aml_rules"] == "FAIL"


def test_path_cap_is_a_registered_bound_kind() -> None:
    from lakebench.metrics import bounds

    entries = bounds.bound_entries({}, {"skipped": {"W3_round_tripping": "path-cap"}}, strict=True)
    assert entries == [("rule W3_round_tripping cap", "rule W3_round_tripping skipped: path-cap")]


def test_giant_component_is_allowed_but_not_a_cap() -> None:
    v = V.verdict_from_record(sr.load_record(AML_BATCH))
    assert v.status == "PASSED" and V.RULE_CAPS not in v.qualifiers


def test_report_labels_the_gold_stage_bounded_by_a_rule_cap() -> None:
    """Invariant 6: skipping W3 and W17 on path-cap shortens gold, so the
    report's gold stage row carries the bound; bronze and silver do not."""
    from lakebench.reports.generator import _stage_matches_cap

    caps = ["rule W3_round_tripping skipped: path-cap"]
    assert _stage_matches_cap("gold", caps)
    assert not _stage_matches_cap("silver", caps)
    assert not _stage_matches_cap("bronze", caps)
    assert not _stage_matches_cap("gold", ["rule W1_connected_components skipped: giant-component"])


# ---------------------------------------------------------------------------
# lakebench benchmark records (record_kind benchmark) are never a run
# ---------------------------------------------------------------------------


def _benchmark_record() -> dict:
    rec = sr.load_record(C360_BATCH)
    rec["record_kind"], rec["parent_run_id"] = "benchmark", rec["run_id"]
    rec["run_id"] = "20261003-000000-be0000"
    return rec


def test_benchmark_record_is_refused_by_release_and_perf_readers() -> None:
    from lakebench.metrics import release_record as rr

    bench = _benchmark_record()
    assert any("a benchmark record" in p for p in rr.record_problems(bench, "f" * 40, {}))


def test_benchmark_record_is_never_the_latest_run(tmp_path: Path) -> None:
    from lakebench.metrics.storage import MetricsStorage

    for rec in (sr.load_record(C360_BATCH), _benchmark_record()):
        d = tmp_path / f"run-{rec['run_id']}"
        d.mkdir()
        (d / "metrics.json").write_text(json.dumps(rec))
    latest = MetricsStorage(tmp_path).get_latest_run_for_deployment(None)
    assert latest is not None and latest.record_kind == "run"


# ---------------------------------------------------------------------------
# verdict_of: one rule for the headline (r3 review)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "stored,success,recomputed,want",
    [
        ("PASSED", True, "PASSED", "PASSED"),
        ("PASSED", True, "FAILED", "FAILED"),
        ("PASSED", True, "REFUSED", "REFUSED"),
        ("PASSED", True, "INTERRUPTED", "INTERRUPTED"),
        ("FAILED", True, "PASSED", "FAILED"),
        ("INTERRUPTED", False, "FAILED", "FAILED"),
        ("REFUSED", True, "INTERRUPTED", "INTERRUPTED"),
        (None, True, "PASSED", "PASSED"),
        (None, False, "PASSED", "FAILED"),
        ("VOID", True, "PASSED", "VOID"),
        ("", True, "PASSED", "FAILED"),
    ],
)
def test_verdict_of_takes_the_strictest(monkeypatch, stored, success, recomputed, want) -> None:
    from types import SimpleNamespace

    monkeypatch.setattr(V, "_recompute", lambda rec: SimpleNamespace(status=recomputed, reasons=[]))
    rec = sr.load_record(C360_BATCH)
    rec["success"] = success
    if stored is None:
        del rec["verdict"]
    else:
        rec["verdict"]["status"] = stored
    got = V.verdict_of(rec)
    assert got == {"stored": stored, "recomputed": recomputed, "status": want}
    assert V.passed(rec) is (want == "PASSED")


def test_verdict_of_an_unreadable_record_is_failed() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["jobs"][0]["start_time"] = "not a time"
    assert V.verdict_of(rec) == {"stored": "PASSED", "recomputed": None, "status": "FAILED"}


def test_verdict_of_a_summary_row_is_what_it_stored() -> None:
    row = {"run_id": "r", "success": True, "verdict": {"status": "PASSED"}}
    assert V.verdict_of(row) == {"stored": "PASSED", "recomputed": None, "status": "PASSED"}


def test_text_report_heads_with_the_strictest_verdict(monkeypatch, tmp_path: Path) -> None:
    from typer.testing import CliRunner

    from lakebench.cli import app

    rec = sr.load_record(C360_BATCH)
    _silver_zero(rec)
    d = tmp_path / "lakebench-output" / "runs" / f"run-{rec['run_id']}"
    d.mkdir(parents=True)
    (d / "metrics.json").write_text(json.dumps(rec))
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("COLUMNS", "200")
    res = CliRunner().invoke(app, ["report", rec["run_id"]])
    text = " ".join(res.output.split())
    assert "Status: Failed (stored PASSED; recomputed FAILED)" in text, text
    res = CliRunner().invoke(app, ["report", "--list"])
    assert "Failed" in res.output and "Passed" not in res.output


def test_benchmark_record_success_follows_its_verdict(tmp_path: Path) -> None:
    """A benchmark record copies its parent's pipeline: when that record
    reads FAILED (a stored pass the record no longer shows), its success is
    False too. The parent's benchmark error stays: it is why the parent
    failed, and the copy keeps the parent's success."""
    import shutil

    from lakebench.cli._query import _save_benchmark_record
    from lakebench.metrics.storage import MetricsStorage
    from tests.test_record_writers import _bench_result

    runs = tmp_path / "runs"
    runs.mkdir()
    rec = sr.load_record(C360_BATCH)
    _silver_zero(rec)
    d = runs / f"run-{rec['run_id']}"
    d.mkdir()
    (d / "metrics.json").write_text(json.dumps(rec))
    storage = MetricsStorage(runs)
    path = _save_benchmark_record(storage, storage.load_run(rec["run_id"]), _bench_result())
    saved = json.loads(Path(path).read_text())
    assert saved["record_kind"] == "benchmark"
    assert saved["success"] is False and saved["verdict"]["status"] == "FAILED"
    assert any("silver has 0 rows" in r for r in saved["verdict"]["reasons"])
    shutil.rmtree(runs)
