"""EVD-1: the verdict is decided from the record alone (DESIGN-v1.7 ch03
section 1, ER-3).

Every case starts from a pinned stored record (tests/fixtures/records) and
edits named fields. The six mutations of the acceptance read PASSED before
ER-3 (compute_verdict had no layer, rule, zero-ratio or empty-answer gate)
and FAILED after it, each on its own gate.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from lakebench.metrics import verdict as V
from tests.fixtures import stored_records as sr

ROOT = Path(__file__).resolve().parents[1]
C360_BATCH = "5105a0"  # C360 batch s10, PASSED
AML_BATCH = "1320bd"  # AML batch s1, PASSED, W1 skipped giant-component
AML_CONT = "ebb26f"  # AML continuous s1, PASSED
C360_CONT = "1d17f4"  # C360 continuous s1, PASSED


def _metrics(rec: dict):
    """*rec* loaded the way lakebench loads a stored run."""
    from lakebench.metrics.storage import MetricsStorage

    return MetricsStorage()._dict_to_metrics(rec)


def _job(rec: dict, job_type: str) -> dict:
    return [j for j in rec["jobs"] if j["job_type"] == job_type][-1]


def _stream(rec: dict, job_type: str) -> dict:
    return [s for s in rec["streaming"] if s["job_type"] == job_type][-1]


def _silver_zero(rec: dict) -> None:
    _job(rec, "silver-build")["output_rows"] = 0


def _gold_zero(rec: dict) -> None:
    _job(rec, "gold-finalize")["output_rows"] = 0
    rec["gold_size_gb"] = 0.0


def _answers_empty(rec: dict) -> None:
    for q in rec["benchmark"]["queries"]:
        q["rows_returned"] = 0


def _ratio_zero(rec: dict) -> None:
    # The loader reads the scorecard (scores is its alias); a save writes
    # the same value in all three places.
    pb = rec["pipeline_benchmark"]
    pb["scale_ratio"] = pb["scorecard"]["scale_ratio"] = pb["scores"]["scale_ratio"] = 0.0


def _rules_errored(rec: dict) -> None:
    gold = _job(rec, "gold-finalize")
    gold["rule_errors"] = dict.fromkeys(gold["alerts_by_rule"], "boom")


def _no_alerts(rec: dict) -> None:
    rec["financial_scoring"]["total_alerts"] = 0


MUTATIONS = {
    "silver_rows_0": (C360_BATCH, _silver_zero, "layer_rows"),
    "gold_rows_and_bytes_0": (C360_BATCH, _gold_zero, "layer_rows"),
    "every_answer_empty": (C360_BATCH, _answers_empty, "query_answers"),
    "scale_ratio_0": (C360_BATCH, _ratio_zero, "scale_ratio"),
    "every_rule_errored": (AML_BATCH, _rules_errored, "aml_rules"),
    "zero_alerts": (AML_BATCH, _no_alerts, "aml_rules"),
}


@pytest.mark.parametrize("name", sorted(MUTATIONS))
def test_mutated_records_fail(name: str) -> None:
    """SPEC EVD-1 acceptance: each mutation FAILS on its own gate."""
    run, mutate, gate = MUTATIONS[name]
    rec = sr.load_record(run)
    mutate(rec)
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED", v.reasons
    assert v.gates[gate] == "FAIL"
    assert f"Gate '{gate}' FAILED" in v.reasons
    assert not V.passed(rec)


@pytest.mark.parametrize("run", [C360_BATCH, AML_BATCH, AML_CONT, C360_CONT])
def test_unmutated_records_pass(run: str) -> None:
    rec = sr.load_record(run)
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED", v.reasons
    for gate, outcome in v.gates.items():
        assert outcome == "PASS", gate
    assert v.qualifiers[V.LAYER_ROWS_UNMEASURED] == []
    assert V.passed(rec)


# ---------------------------------------------------------------------------
# The 24 pinned records: the recomputed verdict, from tests/expected
# ---------------------------------------------------------------------------

RECORD_GATES = {"layer_rows", "aml_rules", "scale_ratio", "query_answers"}
EXPECTED = json.loads((ROOT / "tests" / "expected" / "verdict_recomputed.json").read_text())


@pytest.mark.parametrize("run", sorted(EXPECTED["records"]))
def test_pinned_records_recompute_as_expected(run: str) -> None:
    """Every pinned record's verdict from the record alone, and the gates
    that fail it. A stored pass that reads failed here is listed in
    UPGRADING; the expected file is never regenerated by code."""
    want = EXPECTED["records"][run]
    rec = sr.load_record(run)
    v = V.verdict_from_record(rec)
    assert v.status == want["status"], v.reasons
    failing = sorted(g for g, o in v.gates.items() if o == "FAIL" and g in RECORD_GATES)
    assert failing == want["failing_gates"]
    assert v.qualifiers.get(V.LAYER_ROWS_UNMEASURED) == want["layer_rows_unmeasured"]
    assert V.passed(rec) is (want["status"] == "PASSED")


def test_only_the_listed_stored_passes_flip() -> None:
    """A stored pass (PASSED, or success on a record with no verdict block)
    that recomputes as failed is one of the three listed records."""
    flips = []
    for run in sr.record_ids():
        rec = sr.load_record(run)
        if V.stored_passed(rec) and not V.passed(rec):
            flips.append(run)
    assert flips == sorted(EXPECTED["stored_pass_now_failed"])


# ---------------------------------------------------------------------------
# c360, W1 skips, continuous rules, dependency set
# ---------------------------------------------------------------------------


def test_c360_non_gating_failure_warns() -> None:
    """A failed check outside GATING_CHECKS is shown, never a FAIL."""
    rec = sr.load_record(C360_BATCH)
    check = next(c for c in rec["c360_correctness"]["checks"] if c["id"] == "interaction_mix")
    check["status"] = "fail"
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    assert v.qualifiers["c360_failed_not_gating"] == ["interaction_mix"]
    _ok, _reasons, warnings = V.compute_badge_status(_metrics(rec))
    assert any("interaction_mix" in w and "reporting only" in w for w in warnings)


def test_c360_gated_failure_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    check = next(c for c in rec["c360_correctness"]["checks"] if c["id"] == "silver_to_gold_days")
    check["status"] = "fail"
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["c360"] == "FAIL"


def test_w1_giant_component_skip_passes() -> None:
    rec = sr.load_record(AML_BATCH)
    assert V.verdict_from_record(rec).gates["aml_rules"] == "PASS"
    _job(rec, "gold-finalize")["rules_skipped"]["W1_connected_components"] = "timeout"
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"
    assert any("W1_connected_components skipped (timeout)" in r for r in v.reasons)


def test_w1_vertex_cap_skip_passes() -> None:
    rec = sr.load_record(AML_BATCH)
    _job(rec, "gold-finalize")["rules_skipped"]["W1_connected_components"] = "vertex-cap"
    assert V.verdict_from_record(rec).status == "PASSED"


def test_expected_rule_missing_fails() -> None:
    """A rule that neither ran nor was skipped (left out of the job's
    per-rule counts) fails: nothing was silently skipped."""
    rec = sr.load_record(AML_BATCH)
    del _job(rec, "gold-finalize")["alerts_by_rule"]["W6_pep_counterparty"]
    v = V.verdict_from_record(rec)
    assert v.gates["aml_rules"] == "FAIL"
    assert any("expected rules did not run: W6_pep_counterparty" in r for r in v.reasons)


def test_no_per_rule_counts_is_a_warning_not_a_fail() -> None:
    """With no per-rule counts in the gold log the rule set is not
    measured: the CLI warns, and so does the verdict."""
    rec = sr.load_record(AML_BATCH)
    _job(rec, "gold-finalize")["alerts_by_rule"] = {}
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert any("executed rule set not recorded" in w for w in warnings)


def test_continuous_mode_excluded_rule_ran_fails() -> None:
    rec = sr.load_record(AML_CONT)
    gold = _stream(rec, "gold-refresh")
    gold["ttd_by_rule"]["W1_connected_components"] = {"alerts": 3}
    rec["experiment"]["rules"]["executed"].append("W1_connected_components")
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["aml_rules"] == "FAIL"
    assert any("W1_connected_components" in r for r in v.reasons)


def test_continuous_rule_with_no_alerts_is_not_a_fail() -> None:
    """Continuous knows a rule ran only from its time-to-detect lines, which
    a rule with no alerts does not write."""
    rec = sr.load_record(AML_CONT)
    del _stream(rec, "gold-refresh")["ttd_by_rule"]["W3_round_tripping"]
    assert V.verdict_from_record(rec).status == "PASSED"


def test_pod_set_mismatch_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["provenance"]["deps"] = {"pod_mismatches": [{"pod": "x", "pinset": "a" * 64}]}
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["dependency_set"] == "FAIL"
    del rec["provenance"]["deps"]
    assert "dependency_set" not in V.verdict_from_record(rec).gates


def test_ml_jobs_not_counted() -> None:
    """Only jobs[] carries pipeline layers; a model-training job record
    elsewhere in the record is never counted as a layer."""
    rec = sr.load_record(C360_BATCH)
    rec["ml_jobs"] = [{"job_type": "gold-finalize", "output_rows": 0, "success": True}]
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED" and v.gates["layer_rows"] == "PASS"


# ---------------------------------------------------------------------------
# Layers: continuous sources, bytes fallback, run --stage, failed stages
# ---------------------------------------------------------------------------


def test_aml_continuous_gold_is_measured_by_its_alerts() -> None:
    rec = sr.load_record(AML_CONT)
    assert _stream(rec, "gold-refresh")["output_rows"] is None
    assert V.verdict_from_record(rec).qualifiers[V.LAYER_ROWS_UNMEASURED] == []
    _stream(rec, "gold-refresh")["ttd_alerts"] = None
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    assert v.qualifiers[V.LAYER_ROWS_UNMEASURED] == ["gold"]
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert "rows not measured for gold; bytes > 0" in warnings
    rec["gold_size_gb"] = 0.0
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["layer_rows"] == "FAIL"


def test_continuous_silver_committed_zero_fails() -> None:
    rec = sr.load_record(C360_CONT)
    _stream(rec, "silver-stream")["committed_rows"] = 0
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["layer_rows"] == "FAIL"


def test_batch_missing_stage_job_fails() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] != "gold-finalize"]
    v = V.verdict_from_record(rec)
    assert v.gates["layer_rows"] == "FAIL"
    assert any("no gold-finalize job recorded" in r for r in v.reasons)


def test_stage_only_record_judges_its_layer() -> None:
    """``run --stage silver-build`` runs one stage: the other layers are not
    the run's, and its ratio of 0 is not a missing measurement."""
    rec = sr.load_record(C360_BATCH)
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] == "silver-build"]
    _ratio_zero(rec)
    assert V.verdict_from_record(rec).status == "FAILED"
    rec["stage_only"] = "silver-build"
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED", v.reasons
    _silver_zero(rec)
    assert V.verdict_from_record(rec).gates["layer_rows"] == "FAIL"


def test_failed_stage_adds_no_record_gate() -> None:
    """A failed stage fails the run; the empty layers after it are its
    consequence and add no gate."""
    rec = sr.load_record(C360_BATCH)
    _job(rec, "silver-build")["success"] = False
    rec["jobs"] = [j for j in rec["jobs"] if j["job_type"] != "gold-finalize"]
    v = V.verdict_from_record(rec)
    assert v.status == "FAILED" and v.gates["pipeline"] == "FAIL"
    assert "layer_rows" not in v.gates


def test_interrupted_record_stays_interrupted() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["success"] = False
    rec["interrupted"] = {
        "signal": "SIGINT",
        "at_stage": "gold-finalize",
        "at_utc": "2026-09-29T21:30:00+00:00",
        "prior_failure": False,
    }
    gold = _job(rec, "gold-finalize")
    gold["success"], gold["error_message"], gold["output_rows"] = False, "interrupted", 0
    v = V.verdict_from_record(rec)
    assert v.status == "INTERRUPTED", v.reasons
    assert "layer_rows" not in v.gates


def test_unknown_query_name_is_a_warning() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["benchmark"]["queries"][0].update(name="Q99_renamed", rows_returned=0)
    v = V.verdict_from_record(rec)
    assert v.status == "PASSED"
    _ok, _r, warnings = V.compute_badge_status(_metrics(rec))
    assert any("Q99_renamed" in w for w in warnings)


def test_allow_empty_query_may_return_no_rows() -> None:
    from lakebench.benchmark.queries import BENCHMARK_QUERIES_BY_DOMAIN

    allowed = next(
        q.name for qs in BENCHMARK_QUERIES_BY_DOMAIN.values() for q in qs if q.allow_empty
    )
    rec = sr.load_record(C360_BATCH)
    rec["benchmark"]["queries"][0].update(name=allowed, rows_returned=0)
    assert V.verdict_from_record(rec).gates["query_answers"] == "PASS"


def test_unmeasured_answer_is_not_judged() -> None:
    rec = sr.load_record(C360_BATCH)
    for q in rec["benchmark"]["queries"]:
        q.pop("rows_returned")
    assert V.verdict_from_record(rec).status == "PASSED"


# ---------------------------------------------------------------------------
# Readers: passed() never promotes and recomputes a stored pass
# ---------------------------------------------------------------------------


def test_passed_never_promotes() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["verdict"]["status"] = "FAILED"
    assert V.verdict_from_record(rec).status == "PASSED"
    assert V.passed(rec) is False


def test_passed_recomputes_a_stored_pass() -> None:
    rec = sr.load_record(C360_BATCH)
    assert rec["verdict"]["status"] == "PASSED"
    _silver_zero(rec)
    assert V.stored_passed(rec) is True
    assert V.passed(rec) is False


def test_summary_row_is_judged_on_what_it_stored() -> None:
    """A list_runs row has no jobs list: nothing to recompute from."""
    assert V.passed({"run_id": "r", "success": True, "verdict_status": "PASSED"}) is True
    assert V.passed({"run_id": "r", "success": False}) is False


def test_unreadable_record_reads_not_passed() -> None:
    rec = sr.load_record(C360_BATCH)
    rec["start_time"] = "not a time"
    assert V.passed(rec) is False


def test_fresh_record_reads_back_its_saved_verdict() -> None:
    """The verdict a save writes is the one a reader recomputes."""
    m = sr.load_metrics(C360_BATCH)
    saved = m.to_dict()
    assert V.verdict_from_record(saved).to_dict() == saved["verdict"]
    _job_obj = [j for j in m.jobs if j.job_type == "silver-build"][-1]
    _job_obj.output_rows = 0
    saved = m.to_dict()
    assert saved["verdict"]["status"] == "FAILED"
    assert V.verdict_from_record(saved).to_dict() == saved["verdict"]


# ---------------------------------------------------------------------------
# The CLI's save gate (cli/_run.py, cli/_sustained.py)
# ---------------------------------------------------------------------------


def test_save_gate_fails_a_run_the_record_fails() -> None:
    m = sr.load_metrics(C360_BATCH)
    [j for j in m.jobs if j.job_type == "gold-finalize"][-1].output_rows = 0
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is False
    assert m.success is False
    assert any("gold has 0 rows" in s for s in said)
    assert any("gold has 0 rows" in r for r in m.failure_reasons)
    v = m.to_dict()["verdict"]
    assert v["status"] == "FAILED"
    assert any("gold has 0 rows" in r for r in v["reasons"])
    assert v["gates"]["layer_rows"] == "FAIL"


def test_save_gate_keeps_a_passing_run() -> None:
    m = sr.load_metrics(C360_BATCH)
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is True
    assert m.success is True and said == [] and m.failure_reasons == []


def test_save_gate_leaves_a_failed_run_alone() -> None:
    m = sr.load_metrics(C360_BATCH)
    said: list[str] = []
    assert V.apply_save_gate(m, False, said.append) is False
    assert said == []


def test_save_gate_fails_closed_when_the_record_cannot_be_judged(monkeypatch) -> None:
    m = sr.load_metrics(C360_BATCH)

    def boom(record):
        raise RuntimeError("bad record")

    monkeypatch.setattr(V, "_recompute", boom)
    said: list[str] = []
    assert V.apply_save_gate(m, True, said.append) is False
    assert any("could not be computed" in s for s in said)


@pytest.mark.parametrize("path", ["src/lakebench/cli/_run.py", "src/lakebench/cli/_sustained.py"])
def test_every_cli_save_follows_the_save_gate(path: str) -> None:
    """Each save of a run record is preceded by the save gate, with nothing
    between them that the verdict reads (end samples, corpus observation,
    series seal)."""
    src = (ROOT / path).read_text()
    saves = [
        i for i in range(len(src)) if src.startswith("metrics_storage.save_run(run_metrics)", i)
    ]
    assert saves
    for i in saves:
        window = src[max(0, i - 1500) : i]
        assert "apply_save_gate(run_metrics" in window


# ---------------------------------------------------------------------------
# The release gate reads the real verdict (ER-16's fail-closed inputs)
# ---------------------------------------------------------------------------


def test_release_record_reads_layer_rows_and_expected_skips() -> None:
    from lakebench.metrics import release_record as rr

    assert rr.LAYER_ROWS_UNMEASURED == V.LAYER_ROWS_UNMEASURED
    assert rr._layer_rows_problem(sr.load_record(C360_BATCH)) is None
    assert rr._rules_problems(sr.load_record(AML_BATCH)["experiment"]) == []
    rec = sr.load_record(AML_CONT)
    _stream(rec, "gold-refresh")["ttd_alerts"] = None
    assert rr._layer_rows_problem(rec) == "rows not measured for gold"
    bad = copy.deepcopy(sr.load_record(C360_BATCH))
    _silver_zero(bad)
    assert rr._layer_rows_problem(bad) == "rows per layer: layer_rows gate is FAIL"


# ---------------------------------------------------------------------------
# Through the real run(): the QA-9 harness, one layer emptied after parsing
# ---------------------------------------------------------------------------


def _saved_record(tmp_path: Path) -> dict:
    (path,) = tmp_path.glob("lakebench-output/runs/run-*/metrics.json")
    return json.loads(path.read_text())


def test_batch_run_with_empty_gold_exits_non_zero(tmp_path, monkeypatch) -> None:
    """Every stage succeeds and the CLI's own gates pass, but gold-finalize
    wrote no rows: the run exits 1 and its record reads FAILED on
    layer_rows. Before ER-3 it exited 0 with a PASSED record."""
    from lakebench.metrics.collector import MetricsCollector
    from tests.harness.run_harness import SCENARIOS, invoke_scenario

    real = MetricsCollector.parse_driver_logs

    def gold_empty(self, logs, job_type):
        m = real(self, logs, job_type)
        if job_type == "gold-finalize":
            m.output_rows = 0
        return m

    monkeypatch.setattr(MetricsCollector, "parse_driver_logs", gold_empty)
    result, _rec = invoke_scenario(SCENARIOS["batch_c360"], tmp_path, monkeypatch)
    assert result.exit_code == 1, result.output
    assert "Verdict: gold has 0 rows" in result.output
    saved = _saved_record(tmp_path)
    assert saved["success"] is False
    assert saved["verdict"]["status"] == "FAILED"
    assert saved["verdict"]["gates"]["layer_rows"] == "FAIL"
    assert V.passed(saved) is False


def test_continuous_run_with_empty_gold_exits_non_zero(tmp_path, monkeypatch) -> None:
    """The continuous path: gold-refresh wrote no rows in the window, which
    the CLI's continuous gate (bronze and silver rows) does not check."""
    from lakebench.metrics.collector import StreamingJobMetrics
    from tests.harness.run_harness import SCENARIOS, invoke_scenario

    real = StreamingJobMetrics.apply_window

    def gold_empty(self, logs, start, end):
        stats = real(self, logs, start, end)
        if self.job_type == "gold-refresh":
            self.output_rows = 0
        return stats

    monkeypatch.setattr(StreamingJobMetrics, "apply_window", gold_empty)
    result, _rec = invoke_scenario(SCENARIOS["continuous_c360"], tmp_path, monkeypatch)
    assert result.exit_code == 1, result.output
    assert "Verdict: gold has 0 rows" in result.output
    saved = _saved_record(tmp_path)
    assert saved["success"] is False
    assert saved["verdict"]["status"] == "FAILED"
    assert saved["verdict"]["gates"]["layer_rows"] == "FAIL"
