"""The prose guard: no em dash, emoji or AI attribution in a tracked file.

The tracked-tree test is the gate (it runs in every unit leg); the others
plant each kind in a temporary repository. Planted text is built at run
time so this file passes the scan itself.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from tests.conftest import exec_repo_script

ROOT = Path(__file__).resolve().parents[1]
pg = exec_repo_script(ROOT / "scripts/prose_guard.py", "prose_guard")

EM = chr(0x2014)
ROBOT = chr(0x1F916)
CO = "Co-Authored" + "-By:"
TRAILER = f"{CO} Claude <noreply@example.com>"


def test_tracked_files_are_clean():
    problems = pg.check()
    assert not problems, "prose guard:\n" + "\n".join(problems)


def _git(cwd: Path, *args: str) -> None:
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    git = ["git", "-c", "user.name=t", "-c", "user.email=t@example.com"]
    subprocess.run([*git, *args], cwd=cwd, check=True, env=env, capture_output=True)


def _repo(tmp_path: Path, files: dict[str, str | bytes]) -> Path:
    _git(tmp_path, "init", "-q")
    for rel, body in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(body, bytes):
            p.write_bytes(body)
        else:
            p.write_text(body, encoding="utf-8")
    _git(tmp_path, "add", "-A")
    return tmp_path


def _check(repo: Path, allow: str = "") -> list[str]:
    allowlist = repo / "allow.txt"
    allowlist.write_text(allow)
    return pg.check(root=repo, allowlist=allowlist)


def _kinds(tmp_path: Path, line: str) -> set[str]:
    repo = _repo(tmp_path, {"x.py": f"# {line}\n"})
    hits = pg.scan(["x.py"], repo)
    assert all(h.line == 1 for h in hits)
    return {h.kind for h in hits}


def test_added_em_dash_fails_and_names_line(tmp_path):
    repo = _repo(tmp_path, {"docs/a.md": "fine -- text\n"})
    assert _check(repo) == []
    (repo / "docs/a.md").write_text(f"fine -- text\nbad {EM} here\n")
    key = pg.line_key(f"bad {EM} here")
    assert _check(repo) == [
        f"docs/a.md:2 em-dash -- use `--` or restructure (allowlist key docs/a.md:em-dash:{key})"
    ]


@pytest.mark.parametrize(
    ("line", "kind"),
    [
        (f"bad {EM} here", "em-dash"),
        ("a cell: " + "&" + "mdash;", "em-dash"),
        ("a cell: " + "&#" + "8212;", "em-dash"),
        ("a cell: " + "&#X" + "2014;", "em-dash"),
        (f"done {chr(0x2705)}", "emoji"),
        (f"party {chr(0x1F389)}", "emoji"),
        (f"warn {chr(0x26A0)}{chr(0xFE0F)}", "emoji"),
        (f"star {chr(0x2B50)}", "emoji"),
        (f"waiting {chr(0x23F3)}", "emoji"),
        (f"flag {chr(0x1F1FA)}{chr(0x1F1F8)}", "emoji"),
        (f"ok {chr(0x1F197)}", "emoji"),
        (f"ring {chr(0x2B55)}", "emoji"),
        (TRAILER, "ai-attribution"),
        (f"{CO} Claude Opus <noreply@example.com>", "ai-attribution"),
        ("co-authored" + "-by: someone via Anthropic", "ai-attribution"),
        (f"{CO} GitHub Copilot", "ai-attribution"),
        (f"{CO} Cursor Agent <cursoragent@example.com>", "ai-attribution"),
        (f"{CO} aider (gpt-4o) <noreply@example.com>", "ai-attribution"),
        ("Generated" + "-by: ChatGPT", "ai-attribution"),
        ("Assisted" + "-by: Gemini", "ai-attribution"),
        ("Generated" + " with [Claude Code](https://example.com)", "ai-attribution"),
        ("Written" + " by Claude", "ai-attribution"),
        (f"{ROBOT} Generated with something", "emoji"),
    ],
)
def test_each_kind_is_reported(tmp_path, line, kind):
    assert kind in _kinds(tmp_path, line)


@pytest.mark.parametrize(
    "line",
    [
        f"{CO} A Person <a@example.com>",
        f"{CO} Claudette Smith <c@example.com>",
        "generated by " + "claudelike heuristics",
        f"arrows -> => {chr(0x2192)} and an en dash {chr(0x2013)} and a plain - hyphen",
        "the em dash rule: write -- instead",
    ],
)
def test_ordinary_text_is_not_a_hit(tmp_path, line):
    assert _kinds(tmp_path, line) == set()


def test_robot_credit_line_is_both_emoji_and_attribution(tmp_path):
    assert _kinds(tmp_path, f"{ROBOT} generated by a tool") == {"emoji", "ai-attribution"}


def test_binary_and_large_files_are_skipped_and_listed(tmp_path):
    big = ("x" * 100 + EM + "\n") * (pg.MAX_BYTES // 100 + 1)
    repo = _repo(tmp_path, {"b.bin": b"\0" + EM.encode() + b"\n", "big.txt": big})
    skipped: list[str] = []
    assert pg.scan(["b.bin", "big.txt", "gone.md"], repo, skipped) == []
    assert skipped == ["b.bin", "big.txt", "gone.md"]


def test_undecodable_and_utf16_files_are_hits_not_skips(tmp_path):
    utf16 = f"x {EM}\n".encode("utf-16")
    repo = _repo(tmp_path, {"l1.txt": b"ok\ncaf\xe9\n", "u16.txt": utf16})
    hits = pg.scan(["l1.txt", "u16.txt"], repo)
    assert [(h.path, h.line, h.kind) for h in hits] == [
        ("l1.txt", 2, "undecodable"),
        ("u16.txt", 1, "undecodable"),
    ]


def test_line_numbers_count_newlines_only(tmp_path):
    repo = _repo(tmp_path, {"f.md": f"a\x0cb{chr(0x2028)}c\r\nd {EM}\r\n"})
    assert [h.line for h in pg.scan(["f.md"], repo)] == [2]


def test_allowlisted_hit_passes_moves_with_its_line_and_goes_stale(tmp_path):
    repo = _repo(tmp_path, {"g.md": f"golden {EM}\n"})
    entry = f"g.md:em-dash:{pg.line_key(f'golden {EM}')}  # a rendered UTF-8 golden\n"
    assert _check(repo, entry) == []
    # Lines added above it do not move the entry.
    (repo / "g.md").write_text(f"new\nlines\ngolden {EM}\n")
    assert _check(repo, entry) == []
    (repo / "g.md").write_text("golden --\n")
    problems = _check(repo, entry)
    assert len(problems) == 1 and "stale entry g.md:em-dash:" in problems[0]


def test_stale_allowlist_entry_fails(tmp_path):
    repo = _repo(tmp_path, {"a.md": "clean\n"})
    problems = _check(repo, "a.md:emoji:0123abcd  # was an emoji\n")
    assert problems == [
        "allow.txt: stale entry a.md:emoji:0123abcd (no such hit any more; remove it)"
    ]


@pytest.mark.parametrize(
    "entry",
    ["a.md:em-dash:0123abcd\n", "a.md:em-dash:xyz  # r\n", "a.md:dash:0123abcd  # r\n"],
)
def test_malformed_allowlist_entry_fails(tmp_path, entry):
    repo = _repo(tmp_path, {"a.md": f"x {EM}\n"})
    problems = _check(repo, entry)
    assert any("expected 'path:kind:key  # reason'" in p for p in problems), problems


def test_only_tracked_files_are_scanned(tmp_path):
    repo = _repo(tmp_path, {"a.md": "clean\n"})
    (repo / "untracked.md").write_text(f"x {EM}\n")
    assert _check(repo) == []


def test_an_inherited_git_dir_does_not_redirect_the_scan(tmp_path, monkeypatch):
    # Under a git hook GIT_DIR and GIT_INDEX_FILE name the hook's repository.
    repo = _repo(tmp_path, {"a.md": f"x {EM}\n"})
    monkeypatch.setenv("GIT_DIR", str(ROOT / ".git"))
    monkeypatch.setenv("GIT_INDEX_FILE", str(tmp_path / "no-such-index"))
    assert pg.tracked_files(repo) == ["a.md"]
    assert len(_check(repo)) == 1


def test_tracked_allowlist_is_well_formed():
    entries, bad = pg.load_allowlist()
    assert bad == []
