"""Report goldens: scrubbed stored records rendered to ``tests/fixtures/reports/<run>.html``.

``tests/test_report_consistency.py`` checks today's renderer reproduces each
golden byte for byte. The goldens come from the renderer, so the independent
checks are the record recomputation and the phrases in
``tests/expected/report_goldens.json``. Regenerate after editing both:
``PYTHONPATH=src python3.11 -m tests.fixtures.report_goldens <run>``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

GOLDEN_DIR = Path(__file__).parent / "reports"

GOLDEN_RUNS = ("1320bd", "be2b70", "ebb26f", "5105a0", "1d17f4", "233b69")

_FOOTER = re.compile(r"Generated by Lakebench \| [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9:]{8}")
FOOTER_SCRUBBED = "Generated by Lakebench | (timestamp removed)"


def scrub_timestamp(html: str) -> str:
    """The page with its footer timestamp removed (the one non-record value)."""
    out, n = _FOOTER.subn(FOOTER_SCRUBBED, html)
    if n != 1:
        raise AssertionError(f"expected one footer timestamp, found {n}")
    return out


def render_metrics(metrics) -> str:
    """Today's rendering of a metrics object, timestamp removed."""
    import tempfile

    from lakebench.reports.generator import ReportGenerator

    with tempfile.TemporaryDirectory() as tmp:
        html = ReportGenerator(metrics_dir=tmp)._generate_html(
            metrics, platform_metrics=metrics.platform_metrics
        )
    return scrub_timestamp(html)


def render(run_id: str) -> str:
    """Today's rendering of the fixture record *run_id*, timestamp removed."""
    from tests.fixtures.stored_records import load_metrics

    return render_metrics(load_metrics(run_id))


_DERIVED_SPAN = re.compile(r"<span data-lb-derived=[^>]*>([^<]*)</span>")


def page_text(html: str) -> str:
    """*html* with every derived-number span replaced by its text, for tests
    that look for a rendered phrase."""
    return _DERIVED_SPAN.sub(r"\1", html)


def golden_path(run_id: str) -> Path:
    return GOLDEN_DIR / f"{run_id}.html"


def main(argv: list[str]) -> int:
    runs = argv or list(GOLDEN_RUNS)
    for run_id in runs:
        if run_id not in GOLDEN_RUNS:
            print(f"{run_id} is not a golden run ({', '.join(GOLDEN_RUNS)})", file=sys.stderr)
            return 2
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden_path(run_id).write_text(render(run_id))
        print(f"wrote {golden_path(run_id)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
