"""R0 report goldens (DESIGN-v1.7 ch03 section 15, RPT-2).

Six scrubbed stored records render into ``tests/fixtures/reports/<run>.html``
with the footer timestamp removed. ``tests/test_report_consistency.py``
checks that today's renderer produces each golden byte for byte, that every
derived number on it agrees with its record, and that the hand-written
phrases in ``tests/expected/report_goldens.json`` are on the page.

The goldens are produced by the renderer, so on their own they prove only
that the page did not move. The independent checks are the record
recomputation and the hand-written phrases. There is no pytest flag that
rewrites a golden. A change that moves a page:

1. asserts the number or label it fixes in its own test, computed from the
   record;
2. edits the affected phrases in ``tests/expected/report_goldens.json`` by
   hand, each computed from the record;
3. re-renders the goldens
   (``PYTHONPATH=src python3.11 -m tests.fixtures.report_goldens <run>``);
   a second agent reviews the golden diff against the record before the
   change is ready (SPEC section 6 rule 4).

Known misleading numbers the goldens still carry (each a later RPT-1 fix):
R21 (the bottleneck caption); the continuous bottleneck tables show the
query stage's seconds as milliseconds and sum them into the latency share
(ebb26f, 1d17f4), and 233b69's query CPU share counts Trino cores on a
Spark Thrift run.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

GOLDEN_DIR = Path(__file__).parent / "reports"

# 1320bd AML batch s1 (dirty tree, platform metrics), be2b70 AML batch s10
# FAILED, ebb26f AML continuous, 5105a0 C360 batch s10, 1d17f4 C360
# continuous, 233b69 C360 batch on Spark Thrift.
GOLDEN_RUNS = ("1320bd", "be2b70", "ebb26f", "5105a0", "1d17f4", "233b69")

_FOOTER = re.compile(r"Generated by Lakebench \| [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9:]{8}")
FOOTER_SCRUBBED = "Generated by Lakebench | (timestamp removed)"


def scrub_timestamp(html: str) -> str:
    """The page with its footer timestamp removed (the one non-record value)."""
    out, n = _FOOTER.subn(FOOTER_SCRUBBED, html)
    if n != 1:
        raise AssertionError(f"expected one footer timestamp, found {n}")
    return out


def render(run_id: str) -> str:
    """Today's rendering of the fixture record *run_id*, timestamp removed."""
    import tempfile

    from lakebench.reports.generator import ReportGenerator
    from tests.fixtures.stored_records import load_metrics

    metrics = load_metrics(run_id)
    with tempfile.TemporaryDirectory() as tmp:
        html = ReportGenerator(metrics_dir=tmp)._generate_html(
            metrics, platform_metrics=metrics.platform_metrics
        )
    return scrub_timestamp(html)


_DERIVED_SPAN = re.compile(r"<span data-lb-derived=[^>]*>([^<]*)</span>")


def page_text(html: str) -> str:
    """*html* with every derived-number span replaced by its text, for tests
    that look for a rendered phrase."""
    return _DERIVED_SPAN.sub(r"\1", html)


def golden_path(run_id: str) -> Path:
    return GOLDEN_DIR / f"{run_id}.html"


def main(argv: list[str]) -> int:
    runs = argv or list(GOLDEN_RUNS)
    for run_id in runs:
        if run_id not in GOLDEN_RUNS:
            print(f"{run_id} is not a golden run ({', '.join(GOLDEN_RUNS)})", file=sys.stderr)
            return 2
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden_path(run_id).write_text(render(run_id))
        print(f"wrote {golden_path(run_id)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
