"""Transaction-monitoring operations layer on top of gold.alerts (GOALS P10).

Runs after detection in the AML gold stage (gold_finalize_financial in batch,
gold_refresh_financial in continuous) and turns an alert table into the shape
of a bank's TM operation:

- Stage 1, monitoring completeness: ``gold.tm_reconciliation`` accounts for
  every source payment as monitored or excluded for a stated reason, lists
  data-quality rule failures, and carries the cycle funnel (payments ->
  monitored -> alerts -> escalated -> cases -> SARs). One set of rows per
  cycle (batch) or per operations tick (continuous), appended.
  ``gold.scenario_coverage`` is the scenario-to-typology matrix.
- Stage 6, L1 triage: ``gold.alert_dispositions``. Priority is scenario
  weight x CRR tier. Each alert is closed (``closed_nfa``) or ``escalated``
  by a simulated analyst, ``attached`` to the customer's open case
  (suppression), or ``pending_l1`` while it waits. A QA sample is re-reviewed
  and the disagreement rate kept.
- Stage 7, L2 cases: ``gold.cases``, keyed on the customer, at most one open
  case per customer, pulling every open alert plus the lookback window of
  activity.
- Stage 8, SAR decision: ``sar_filed`` / ``no_sar`` with the clocks:
  alert-to-decision aging against a policy SLA; determination-to-filing
  against 31 CFR 1020.320 (30 days, 60 when no suspect is identified); and
  for continuing activity the FinCEN limit of 120 days after the prior SAR,
  with the review opened 90 days after each SAR.

Dispositions are SIMULATED from ground truth. An alert is truly suspicious
when it touches a planted (non-control) typology transaction in the datagen
manifest; the L1 analyst decides correctly with probability
``analyst_accuracy`` and the L2 investigator with ``investigator_accuracy``.
Every random draw is a hash of (seed, draw name, a stable key), not of
arrival order.

Alert identity and history. An alert keeps the identity it was first seen
with (``alert_key``). The next cycle reads the previous cycle's dispositions
and matches each alert to it: the same content (rule, entity, time, related
payments) first, else the same rule on the same customer whose pattern
extended forward by at most ``EXTENSION_MATCH_DAYS`` (a window that grew as
the corpus grew). A matched alert keeps its key, generated date, truth and
priority as first seen; an alert that detection no longer emits is carried
forward (``in_current_detection`` false) rather than erased; an alert first
seen this cycle whose last payment predates the previous cycle is dated on
this cycle's as-of date, the first day the overnight run could have raised
it. The day-by-day replay is causal (a decision on day d depends only on
alerts generated by day d) and its inputs for every already-seen alert are
frozen, so recomputing it reproduces every decision up to the previous
as-of date exactly. The ``history_stable`` invariant checks that on the
written tables against the previous cycle's snapshot.

Time. The unit of work is the business day. An alert is generated the day
after its last contributing payment (the overnight scenario run), and the
workflow is replayed day by day up to the cycle's as-of date (the day after
the newest payment in the silver snapshot). Decisions dated after the as-of
date have not happened yet: those alerts and cases are the open backlog.

Continuous behaviour. gold_refresh runs this layer every
``continuous_interval_seconds`` (not every tick: at scale 10 one pass costs
minutes). Silver is read at one pinned snapshot, taken before the source
files are counted, so payments datagen wrote after the snapshot count as
``in_flight`` and never as a negative.

Workflow invariants (P10.2) are checked against the tables as written, read
back, and logged as ``[tm-invariant]`` lines; ``[tm-status]`` says whether
the layer ran and why not; a ``[tm-ops]`` JSON line carries the operations
summary for the scorecard.
"""

from __future__ import annotations

import hashlib
import heapq
import json
import re
from datetime import date, timedelta

from common import env, iceberg_table_stats, log, one_line

CATALOG = env("LB_ICEBERG_CATALOG", "lakehouse")
GOLD_ALERTS = env("LB_FINANCIAL_GOLD_ALERTS", "gold.alerts")
GOLD_STATUS = env("LB_FINANCIAL_GOLD_DETECTION_STATUS", "gold.detection_status")
GOLD_RECON = env("LB_FINANCIAL_GOLD_TM_RECONCILIATION", "gold.tm_reconciliation")
GOLD_COVERAGE = env("LB_FINANCIAL_GOLD_SCENARIO_COVERAGE", "gold.scenario_coverage")
GOLD_DISPOSITIONS = env("LB_FINANCIAL_GOLD_ALERT_DISPOSITIONS", "gold.alert_dispositions")
GOLD_CASES = env("LB_FINANCIAL_GOLD_CASES", "gold.cases")
SILVER_TXNS = env("LB_FINANCIAL_SILVER_TRANSACTIONS", "silver.transactions")
SILVER_ENTITIES = env("LB_FINANCIAL_SILVER_ENTITIES", "silver.entities")
BRONZE_TABLE = env("LB_FINANCIAL_BRONZE_TABLE", "default.pacs008_raw")
MANIFEST_TABLE = env("LB_FINANCIAL_MANIFEST_TABLE", "bronze.manifest")

# Graph scenarios run as an advanced-analytics overlay across the whole
# payment network (GOALS P10 stage 4), so they are declared to alert on
# counterparties as well as customers. Every other scenario alerts on
# customers only; an alert from one of them on a non-customer fails the
# ``noncustomer_alerts_declared`` invariant. detection_rules restricts every
# other rule's subject to customers (CUSTOMER_SCOPED_RULES) and carries the
# same list as COUNTERPARTY_SCENARIOS; tests assert the copies match.
DEFAULT_COUNTERPARTY_SCENARIOS = (
    "W1_connected_components",
    "W3_round_tripping",
    "W4_risk_propagation",
    "W17_layering_chain",
)


def _float_env(name, default):
    try:
        return float(env(name, str(default)))
    except ValueError:
        return float(default)


def _int_env(name, default):
    try:
        return int(env(name, str(default)))
    except ValueError:
        return int(default)


def params_from_env() -> dict:
    """Workflow parameters (``workload.tm_operations`` in the config)."""
    scen = env("LB_TM_COUNTERPARTY_SCENARIOS", ",".join(DEFAULT_COUNTERPARTY_SCENARIOS))
    return {
        "enabled": env("LB_TM_ENABLED", "true").strip().lower() not in ("false", "0", "no"),
        "seed": _int_env("LB_TM_SEED", 20260924),
        "analyst_accuracy": _float_env("LB_TM_ANALYST_ACCURACY", 0.90),
        "investigator_accuracy": _float_env("LB_TM_INVESTIGATOR_ACCURACY", 0.95),
        "qa_sample_rate": _float_env("LB_TM_QA_SAMPLE_RATE", 0.05),
        "alert_sla_days": _int_env("LB_TM_ALERT_SLA_DAYS", 60),
        "lookback_months": _int_env("LB_TM_CASE_LOOKBACK_MONTHS", 12),
        "late_filing_rate": _float_env("LB_TM_LATE_FILING_RATE", 0.03),
        "no_suspect_rate": _float_env("LB_TM_NO_SUSPECT_RATE", 0.05),
        "max_alerts_per_customer": _int_env("LB_TM_MAX_ALERTS_PER_CUSTOMER", 50_000),
        "continuous_interval_seconds": _int_env("LB_TM_CONTINUOUS_INTERVAL_S", 1800),
        "counterparty_scenarios": tuple(s.strip() for s in scen.split(",") if s.strip()),
    }


# ---------------------------------------------------------------------------
# DDL. Mirrored in src/lakebench/deploy/financial_ddl.py; a test holds the two
# column lists in lock-step.
# ---------------------------------------------------------------------------

DDL_RECON = f"""
CREATE TABLE IF NOT EXISTS {CATALOG}.{GOLD_RECON} (
    run_id         STRING NOT NULL,
    cycle          INT NOT NULL,
    cycle_run_id   STRING NOT NULL,
    as_of_date     DATE,
    section        STRING NOT NULL,
    item           STRING NOT NULL,
    unit           STRING NOT NULL,
    item_count     BIGINT,
    amount_usd     DECIMAL(38, 2),
    computed_ts    TIMESTAMP NOT NULL
) USING iceberg
TBLPROPERTIES ('format-version' = '2', 'write.parquet.compression-codec' = 'snappy')
"""

DDL_COVERAGE = f"""
CREATE TABLE IF NOT EXISTS {CATALOG}.{GOLD_COVERAGE} (
    typology             STRING,
    rule_id              STRING,
    coverage             STRING NOT NULL,
    rule_status          STRING,
    alert_count          BIGINT,
    customer_alert_count BIGINT,
    planted_instances    BIGINT,
    run_id               STRING NOT NULL,
    computed_ts          TIMESTAMP NOT NULL
) USING iceberg
TBLPROPERTIES ('format-version' = '2', 'write.parquet.compression-codec' = 'snappy')
"""

DDL_DISPOSITIONS = f"""
CREATE TABLE IF NOT EXISTS {CATALOG}.{GOLD_DISPOSITIONS} (
    alert_id              STRING NOT NULL,
    alert_key             STRING NOT NULL,
    rule_id               STRING NOT NULL,
    entity_id             BIGINT NOT NULL,
    is_customer           BOOLEAN NOT NULL,
    declared_counterparty BOOLEAN NOT NULL,
    crr_tier              STRING,
    scenario_weight       DOUBLE NOT NULL,
    priority_score        DOUBLE NOT NULL,
    triage_priority       STRING NOT NULL,
    alert_ts              TIMESTAMP,
    content_hash          STRING,
    first_seen_cycle      INT,
    first_seen_as_of      DATE,
    in_current_detection  BOOLEAN NOT NULL,
    generated_date        DATE NOT NULL,
    l1_decision_date      DATE,
    disposition           STRING NOT NULL,
    queue_status          STRING NOT NULL,
    case_id               STRING,
    decision_date         DATE,
    aging_days            INT NOT NULL,
    sla_breached          BOOLEAN NOT NULL,
    simulated_truth       BOOLEAN NOT NULL,
    analyst_correct       BOOLEAN,
    qa_sampled            BOOLEAN NOT NULL,
    qa_disposition        STRING,
    qa_disagrees          BOOLEAN,
    as_of_date            DATE NOT NULL,
    cycle                 INT NOT NULL,
    base_run_id           STRING NOT NULL,
    run_id                STRING NOT NULL,
    computed_ts           TIMESTAMP NOT NULL
) USING iceberg
TBLPROPERTIES ('format-version' = '2', 'write.parquet.compression-codec' = 'snappy')
"""

DDL_CASES = f"""
CREATE TABLE IF NOT EXISTS {CATALOG}.{GOLD_CASES} (
    case_id                        STRING NOT NULL,
    customer_id                    BIGINT NOT NULL,
    case_type                      STRING NOT NULL,
    parent_case_id                 STRING,
    opened_date                    DATE NOT NULL,
    crr_tier                       STRING,
    priority                       STRING NOT NULL,
    alert_count                    INT NOT NULL,
    escalated_alert_count          INT NOT NULL,
    rule_ids                       ARRAY<STRING>,
    first_alert_date               DATE,
    activity_window_start          DATE NOT NULL,
    activity_window_end            DATE NOT NULL,
    activity_txn_count             BIGINT,
    activity_amount_usd            DECIMAL(38, 2),
    case_status                    STRING NOT NULL,
    determination                  STRING,
    determination_date             DATE,
    sar_decision                   STRING,
    suspect_identified             BOOLEAN NOT NULL,
    regulatory_limit               STRING,
    filing_deadline_date           DATE,
    filing_date                    DATE,
    determination_to_filing_days   INT,
    days_since_prior_sar           INT,
    filed_late                     BOOLEAN,
    alert_to_decision_days         INT,
    sla_breached                   BOOLEAN NOT NULL,
    continuing_review_due_date     DATE,
    continuing_review_status       STRING,
    continuing_review_case_id      STRING,
    simulated_truth                BOOLEAN NOT NULL,
    as_of_date                     DATE NOT NULL,
    cycle                          INT NOT NULL,
    base_run_id                    STRING NOT NULL,
    run_id                         STRING NOT NULL,
    computed_ts                    TIMESTAMP NOT NULL
) USING iceberg
TBLPROPERTIES ('format-version' = '2', 'write.parquet.compression-codec' = 'snappy')
"""

TM_DDLS = (
    ("tm_reconciliation", DDL_RECON),
    ("scenario_coverage", DDL_COVERAGE),
    ("alert_dispositions", DDL_DISPOSITIONS),
    ("cases", DDL_CASES),
)
TM_TABLES = (GOLD_RECON, GOLD_COVERAGE, GOLD_DISPOSITIONS, GOLD_CASES)

_DDL_COLUMN = re.compile(r"^\s+([a-z_0-9]+)\s+([A-Z][A-Z0-9_]*(?:\([^)]*\))?(?:<[^>]*>)?)", re.M)


def ddl_columns(ddl: str) -> list[tuple[str, str]]:
    """(name, type) per column of a CREATE TABLE statement above."""
    return [(n, t) for n, t in _DDL_COLUMN.findall(ddl) if n not in ("using",)]


def bootstrap_tm_tables(spark) -> None:
    """Create the TM tables (and their namespaces, which the Hive catalog does
    not pre-create). A table left by an earlier build that lacks a column is
    upgraded in place with a nullable ADD COLUMNS."""
    from common import ensure_column, ensure_namespaces_for_ddl

    ensure_namespaces_for_ddl(spark, CATALOG, [ddl for _, ddl in TM_DDLS])
    for (name, ddl), table in zip(TM_DDLS, TM_TABLES):  # noqa: B905 -- Python 3.9 image
        spark.sql(ddl)
        fq = f"{CATALOG}.{table}"
        existing = set(spark.table(fq).columns)
        for col_name, sql_type in ddl_columns(ddl):
            if col_name not in existing:
                ensure_column(spark, fq, col_name, sql_type)
        log(f"Bootstrapped gold.{name}")


# ---------------------------------------------------------------------------
# Triage priority (stage 6)
# ---------------------------------------------------------------------------

# Scenario weight: how much an alert of this scenario is worth an analyst's
# time before anything is known about the customer. Network and round-trip
# scenarios score highest; W4 rapid pass-through is the noisiest scenario and
# scores lowest.
SCENARIO_WEIGHT = {
    "W1_connected_components": 3.0,
    "W3_round_tripping": 3.0,
    "W17_layering_chain": 3.0,
    "W5_sanctions_match": 3.0,
    "W2_structuring": 2.0,
    "W6_pep_counterparty": 2.0,
    "W7_cross_border_high_risk": 2.0,
    "W8_dormant_reactivation": 2.0,
    "W4_risk_propagation": 1.0,
}
DEFAULT_SCENARIO_WEIGHT = 1.0
# Customer risk rating tier multiplier. A non-customer or unrated party
# counts as low.
CRR_MULTIPLIER = {"low": 1.0, "medium": 2.0, "high": 3.0}
# priority_score = weight x CRR multiplier, in [1, 9]. Thresholds below.
PRIORITY_BANDS = ((6.0, "critical"), (4.0, "high"), (2.0, "medium"), (0.0, "low"))
PRIORITY_RANK = {"low": 0, "medium": 1, "high": 2, "critical": 3}


def triage_priority(score: float) -> str:
    for floor, name in PRIORITY_BANDS:
        if score >= floor:
            return name
    return "low"


# ---------------------------------------------------------------------------
# Workflow clocks and simulated turnaround
# ---------------------------------------------------------------------------

# L1 turnaround by priority: the queue is worked highest priority first, so a
# critical alert is decided in days and a low one waits weeks.
L1_TURNAROUND_DAYS = {
    "critical": (1, 3),
    "high": (1, 7),
    "medium": (2, 14),
    "low": (3, 21),
}
INVESTIGATION_DAYS = (10, 60)
# A continuing-activity review is scoped to the activity since the prior SAR
# and has to leave time to file inside the 120-day limit below.
REVIEW_INVESTIGATION_DAYS = (5, 20)
# Filing lag after determination: inside the deadline normally, and this many
# days past it for the late share.
LATE_FILING_EXTRA_DAYS = (1, 15)
# 31 CFR 1020.320(d): file within 30 calendar days of the initial
# determination of facts; a further 30 (60 in total) when no suspect is
# identified.
FILING_DEADLINE_DAYS = 30
FILING_DEADLINE_NO_SUSPECT_DAYS = 60
# FinCEN SAR FAQ: review continuing activity 90 days after the SAR is filed,
# and file the continuing-activity SAR within 120 days of the prior SAR.
CONTINUING_REVIEW_DAYS = 90
CONTINUING_FILING_LIMIT_DAYS = 120
# How far forward an alert's last payment may move between cycles and still be
# the same alert (its window grew with the corpus). Beyond this it is new
# activity and a new alert.
EXTENSION_MATCH_DAYS = 31

# Alert queue aging buckets (P10.3 queue health).
AGING_BUCKETS = ((0, 30, "0-30"), (31, 60, "31-60"), (61, 90, "61-90"), (91, None, "90+"))

# Dispositions. Every alert row carries one (never NULL).
DISP_ESCALATED = "escalated"
DISP_CLOSED = "closed_nfa"
DISP_ATTACHED = "attached"
DISP_PENDING = "pending_l1"
DISP_OUT_OF_SCOPE = "out_of_scope"
DISP_OVER_CAPACITY = "over_capacity"
WORKED_DISPOSITIONS = (DISP_ESCALATED, DISP_CLOSED, DISP_ATTACHED)


def aging_bucket(days: int) -> str:
    for lo, hi, name in AGING_BUCKETS:
        if days >= lo and (hi is None or days <= hi):
            return name
    return "0-30"


def draw(seed: int, name: str, key: str) -> float:
    """Uniform [0, 1) from a hash of (seed, draw name, content key)."""
    h = hashlib.sha256(f"{seed}|{name}|{key}".encode()).digest()
    return int.from_bytes(h[:8], "big") / 2.0**64


def draw_int(seed: int, name: str, key: str, lo: int, hi: int) -> int:
    return lo + min(hi - lo, int(draw(seed, name, key) * (hi - lo + 1)))


def add_months(d: date, months: int) -> date:
    m = d.month - 1 + months
    y = d.year + m // 12
    m = m % 12 + 1
    days_in = [31, 29 if (y % 4 == 0 and (y % 100 != 0 or y % 400 == 0)) else 28]
    days_in += [31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    return date(y, m, min(d.day, days_in[m - 1]))


def filing_deadline(determination: date, suspect_identified: bool) -> date:
    days = FILING_DEADLINE_DAYS if suspect_identified else FILING_DEADLINE_NO_SUSPECT_DAYS
    return determination + timedelta(days=days)


def case_id_for(customer_id: int, opened: date, case_type: str) -> str:
    raw = f"{customer_id}|{opened.isoformat()}|{case_type}"
    return "case-" + hashlib.sha256(raw.encode()).hexdigest()[:24]


# ---------------------------------------------------------------------------
# Alert identity across cycles (pure Python; runs on executors)
# ---------------------------------------------------------------------------


_MICROS_PER_DAY = 86_400 * 1_000_000


def _ts(a):
    return a["alert_ts"] if a["alert_ts"] is not None else -1


def match_alerts(current, prior, prev_as_of, as_of, cycle):
    """This cycle's alerts on one customer, with their identity carried.

    ``current``: dicts alert_id, alert_key, content_hash, rule_id, alert_ts
    (epoch microseconds: a Python datetime would take the executor's local
    zone), generated_date (the day after the last payment), truth, triage_priority,
    priority_score, scenario_weight. ``prior``: the previous cycle's rows for
    the customer, same keys plus first_seen_cycle and first_seen_as_of.

    Returns alert dicts for :func:`simulate_customer`: matched alerts keep the
    prior key and frozen attributes, withdrawn prior alerts are carried with
    ``in_current_detection`` false, and new alerts are dated no earlier than
    the first cycle that could have raised them.
    """
    out = []
    # Every prior key is taken, matched or not: a new alert must never be
    # handed the key of a prior alert carried as withdrawn.
    used = {p["alert_key"] for p in prior}
    by_content = {}
    for p in sorted(prior, key=lambda x: (_ts(x), x["alert_key"])):
        by_content.setdefault(p["content_hash"], []).append(p)

    def carry(p, cur):
        a = dict(p)
        a["alert_id"] = cur["alert_id"] if cur is not None else p["alert_id"]
        a["in_current_detection"] = cur is not None
        if cur is not None:
            # The alert as detection emits it now; the workflow attributes
            # stay as first seen.
            a["alert_ts"] = cur["alert_ts"]
            a["content_hash"] = cur["content_hash"]
        used.add(a["alert_key"])
        out.append(a)

    cur_sorted = sorted(current, key=lambda x: (_ts(x), x["content_hash"], x["alert_key"]))
    unmatched = []
    for c in cur_sorted:
        same = by_content.get(c["content_hash"])
        if same:
            carry(same.pop(0), c)
        else:
            unmatched.append(c)
    remaining = {}
    for lst in by_content.values():
        for p in lst:
            remaining.setdefault(p["rule_id"], []).append(p)
    window = EXTENSION_MATCH_DAYS * _MICROS_PER_DAY
    for c in unmatched:
        cands = remaining.get(c["rule_id"]) or []
        best = None
        for p in cands:
            if p["alert_ts"] is None or c["alert_ts"] is None:
                continue
            # The earliest prior this alert could have grown from: with
            # current alerts taken in time order this pairs grown windows in
            # order instead of letting an early alert take a later one's key.
            if p["alert_ts"] <= c["alert_ts"] <= p["alert_ts"] + window:
                if best is None or p["alert_ts"] < best["alert_ts"]:
                    best = p
        if best is not None:
            cands.remove(best)
            carry(best, c)
            continue
        a = dict(c)
        raw = c["generated_date"]
        if prev_as_of is not None and raw <= prev_as_of:
            # Not raised by the previous cycle although its payments were
            # already there: the first run that could raise it is this one.
            a["generated_date"] = as_of
        key = a["alert_key"]
        while key in used:
            key += "+"
        a["alert_key"] = key
        used.add(key)
        a["first_seen_cycle"] = cycle
        a["first_seen_as_of"] = as_of
        a["in_current_detection"] = True
        out.append(a)
    for lst in remaining.values():
        for p in lst:
            carry(p, None)
    return out


# ---------------------------------------------------------------------------
# Per-customer workflow replay (pure Python; runs on executors)
# ---------------------------------------------------------------------------

# Event order within one day: a case closing frees the customer before a
# review opens, reviews and L1 decisions open cases before the day's new
# alerts arrive, so a same-day arrival attaches to a case opened that day.
_EV_CLOSE, _EV_DETERMINE, _EV_REVIEW, _EV_L1, _EV_ARRIVE = range(5)


def simulate_customer(customer_id, crr_tier, alerts, params, as_of):
    """Replay one customer's alerts through L1, L2 and SAR filing.

    ``alerts``: dicts with alert_id, alert_key, rule_id, generated_date,
    truth, triage_priority, priority_score (other keys pass through). ``as_of``:
    the cycle's business date; nothing dated later has happened.

    Returns ``(dispositions, cases)``: lists of dicts, one per alert and one
    per case.
    """
    seed = int(params["seed"])
    l1_acc = float(params["analyst_accuracy"])
    l2_acc = float(params["investigator_accuracy"])
    qa_rate = float(params["qa_sample_rate"])
    sla = int(params["alert_sla_days"])
    lookback = int(params["lookback_months"])
    late_rate = float(params["late_filing_rate"])
    no_suspect_rate = float(params.get("no_suspect_rate", 0.0))

    st = {}  # alert_key -> mutable state
    pending = {}  # alert keys awaiting L1, in arrival order (dict as ordered set)
    cases = []
    open_case = [None]
    deferred_reviews = []  # parents whose review waits for a determined case to close
    events = []
    seq = [0]
    by_id = {}

    def push(day, kind, ref):
        seq[0] += 1
        heapq.heappush(events, (day, kind, seq[0], ref))

    for a in sorted(alerts, key=lambda x: (x["generated_date"], x["alert_key"])):
        st[a["alert_key"]] = {
            "a": a,
            "disposition": None,
            "l1_date": None,
            "case": None,
            "decision_date": None,
            "correct": None,
        }
        push(a["generated_date"], _EV_ARRIVE, a["alert_key"])

    def link(s, case, disposition, day):
        s["disposition"] = disposition
        s["case"] = case
        case["alert_keys"].append(s["a"]["alert_key"])
        if case["determination_date"] is not None:
            # Determination already made (SAR being filed): the alert is
            # reviewed as continuing activity on attachment.
            s["decision_date"] = max(day, case["determination_date"])

    def open_new_case(day, case_type, parent=None):
        cid = case_id_for(customer_id, day, case_type)
        continuing = case_type == "continuing_activity"
        case = {
            "case_id": cid,
            "case_type": case_type,
            "parent": parent,
            "opened_date": day,
            "alert_keys": [],
            "escalated": 0,
            "determination": None,
            "determination_date": None,
            "sar_decision": None,
            "filing_date": None,
            "filing_deadline": None,
            "regulatory_limit": None,
            "close_date": None,
            "review_due": None,
            "review_case_id": None,
            "review_status": None,
            # The subject of a continuing-activity review is the SAR's
            # subject; a new case may not have identified one.
            "suspect": continuing or draw(seed, "no_suspect", cid) >= no_suspect_rate,
            "truth": False,
            "review_since": parent["filing_date"] if parent else None,
        }
        cases.append(case)
        by_id[cid] = case
        open_case[0] = case
        # Suppression and case scope: every alert still waiting for L1 on
        # this customer joins the case.
        for k in list(pending):
            link(st[k], case, DISP_ATTACHED, day)
        pending.clear()
        span = REVIEW_INVESTIGATION_DAYS if continuing else INVESTIGATION_DAYS
        inv = draw_int(seed, "investigation", cid, *span)
        push(day + timedelta(days=inv), _EV_DETERMINE, cid)
        return case

    def open_review(day, parents):
        rc = open_new_case(day, "continuing_activity", parent=parents[0])
        for p in parents:
            p["review_case_id"] = rc["case_id"]
            p["review_status"] = "opened"

    while events:
        day, kind, _, ref = heapq.heappop(events)
        if day > as_of:
            break
        if kind == _EV_ARRIVE:
            s = st[ref]
            if open_case[0] is not None:
                link(s, open_case[0], DISP_ATTACHED, day)
            else:
                lo, hi = L1_TURNAROUND_DAYS[s["a"]["triage_priority"]]
                pending[ref] = True
                push(
                    day + timedelta(days=draw_int(seed, "l1_turnaround", ref, lo, hi)), _EV_L1, ref
                )
        elif kind == _EV_L1:
            s = st[ref]
            if ref not in pending:
                continue  # attached to a case before its turn came
            del pending[ref]
            s["l1_date"] = day
            correct = draw(seed, "l1", ref) < l1_acc
            truth = bool(s["a"]["truth"])
            s["correct"] = correct
            if truth == correct:  # escalate: right on a true alert, wrong on a false one
                case = open_case[0]
                if case is None:
                    case = open_new_case(day, "alert_escalation")
                link(s, case, DISP_ESCALATED, day)
                case["escalated"] += 1
            else:
                s["disposition"] = DISP_CLOSED
                s["decision_date"] = day
        elif kind == _EV_DETERMINE:
            case = by_id[ref]
            members = [st[k] for k in case["alert_keys"]]
            continuing = case["case_type"] == "continuing_activity"
            if continuing:
                since = case["review_since"]
                truth = any(
                    x["a"]["truth"] and since < x["a"]["generated_date"] <= day for x in st.values()
                )
            else:
                truth = any(m["a"]["truth"] for m in members)
            case["truth"] = truth
            correct = draw(seed, "l2", case["case_id"]) < l2_acc
            suspicious = truth == correct
            case["determination_date"] = day
            for m in members:
                m["decision_date"] = day
            if suspicious:
                case["determination"] = "suspicious"
                deadline = filing_deadline(day, case["suspect"])
                limit = "30_day" if case["suspect"] else "60_day_no_suspect"
                if continuing:
                    prior_sar = case["parent"]["filing_date"]
                    cap = prior_sar + timedelta(days=CONTINUING_FILING_LIMIT_DAYS)
                    if cap < deadline:
                        deadline, limit = cap, "120_day_continuing"
                case["filing_deadline"] = deadline
                case["regulatory_limit"] = limit
                room = (deadline - day).days
                if draw(seed, "late_filing", case["case_id"]) < late_rate:
                    lag = room + draw_int(
                        seed, "filing_days", case["case_id"], *LATE_FILING_EXTRA_DAYS
                    )
                else:
                    # Inside the deadline; a determination made with under
                    # two days left files late, and says so.
                    lag = draw_int(seed, "filing_days", case["case_id"], 2, max(2, room - 2))
                push(day + timedelta(days=lag), _EV_CLOSE, case["case_id"])
            else:
                case["determination"] = "not_suspicious"
                case["sar_decision"] = "no_sar"
                case["close_date"] = day
                open_case[0] = None
        elif kind == _EV_CLOSE:
            case = by_id[ref]
            case["sar_decision"] = "sar_filed"
            case["filing_date"] = day
            case["close_date"] = day
            case["review_due"] = day + timedelta(days=CONTINUING_REVIEW_DAYS)
            open_case[0] = None
            push(case["review_due"], _EV_REVIEW, case["case_id"])
            if deferred_reviews:
                # Reviews that fell due while this case was waiting to file:
                # the SAR it just filed covers the customer's activity to
                # date, so it is the continuing-activity filing for them.
                for p in deferred_reviews:
                    p["review_case_id"] = case["case_id"]
                    p["review_status"] = "superseded_by_sar"
                deferred_reviews.clear()
        elif kind == _EV_REVIEW:
            parent = by_id[ref]
            oc = open_case[0]
            if oc is None:
                open_review(day, [parent])
            elif oc["determination_date"] is None:
                # The customer is under investigation: the review is folded
                # into the open case, whose determination covers it.
                parent["review_case_id"] = oc["case_id"]
                parent["review_status"] = "folded"
            else:
                # The open case is already determined and only waiting to
                # file; it reviews nothing new. Its SAR, once filed, is the
                # continuing-activity filing (see _EV_CLOSE).
                parent["review_status"] = "deferred"
                deferred_reviews.append(parent)

    dispositions = []
    for k, s in st.items():
        a = s["a"]
        decided = s["decision_date"]
        aging = max(0, ((decided or as_of) - a["generated_date"]).days)
        qa_sampled = s["l1_date"] is not None and draw(seed, "qa_pick", k) < qa_rate
        qa_disp = None
        qa_dis = None
        if qa_sampled:
            qa_correct = draw(seed, "qa", k) < l2_acc
            qa_disp = DISP_ESCALATED if bool(a["truth"]) == qa_correct else DISP_CLOSED
            l1_disp = DISP_ESCALATED if s["disposition"] == DISP_ESCALATED else DISP_CLOSED
            qa_dis = qa_disp != l1_disp
        row = {x: a.get(x) for x in _PASS_THROUGH if x in a}
        row.update(
            {
                "alert_id": a["alert_id"],
                "alert_key": k,
                "l1_decision_date": s["l1_date"],
                "disposition": s["disposition"] or DISP_PENDING,
                "queue_status": "closed" if decided is not None else "open",
                "case_id": s["case"]["case_id"] if s["case"] else None,
                "decision_date": decided,
                "aging_days": aging,
                "sla_breached": aging > sla,
                "analyst_correct": s["correct"],
                "qa_sampled": qa_sampled,
                "qa_disposition": qa_disp,
                "qa_disagrees": qa_dis,
            }
        )
        dispositions.append(row)

    out_cases = []
    for c in cases:
        members = [st[k]["a"] for k in c["alert_keys"]]
        first = min((m["generated_date"] for m in members), default=None)
        rank = max((PRIORITY_RANK[m["triage_priority"]] for m in members), default=1)
        priority = [p for p, r in PRIORITY_RANK.items() if r == rank][0]
        det = c["determination_date"]
        start_clock = first or c["opened_date"]
        a2d = max(0, ((det or as_of) - start_clock).days)
        filing_days = (c["filing_date"] - det).days if c["filing_date"] and det else None
        prior_sar_days = None
        if c["parent"] is not None and c["filing_date"] is not None:
            prior_sar_days = (c["filing_date"] - c["parent"]["filing_date"]).days
        if c["close_date"] is not None:
            status = "closed"
        elif det is not None:
            status = "pending_filing"
        else:
            status = "open"
        out_cases.append(
            {
                "case_id": c["case_id"],
                "customer_id": customer_id,
                "case_type": c["case_type"],
                "parent_case_id": c["parent"]["case_id"] if c["parent"] else None,
                "opened_date": c["opened_date"],
                "crr_tier": crr_tier,
                "priority": priority,
                "alert_count": len(members),
                "escalated_alert_count": c["escalated"],
                "rule_ids": sorted({m["rule_id"] for m in members}),
                "first_alert_date": first,
                "activity_window_start": add_months(c["opened_date"], -lookback),
                "activity_window_end": c["opened_date"],
                "case_status": status,
                "determination": c["determination"],
                "determination_date": det,
                "sar_decision": c["sar_decision"],
                "suspect_identified": bool(c["suspect"]),
                "regulatory_limit": c["regulatory_limit"],
                "filing_deadline_date": c["filing_deadline"],
                "filing_date": c["filing_date"],
                "determination_to_filing_days": filing_days,
                "days_since_prior_sar": prior_sar_days,
                "filed_late": (
                    c["filing_date"] > c["filing_deadline"]
                    if c["filing_date"] and c["filing_deadline"]
                    else None
                ),
                "alert_to_decision_days": a2d,
                "sla_breached": a2d > sla,
                "continuing_review_due_date": c["review_due"],
                "continuing_review_status": c["review_status"],
                "continuing_review_case_id": c["review_case_id"],
                "simulated_truth": bool(c["truth"]),
            }
        )
    return dispositions, out_cases


# Alert attributes the replay passes through to the disposition row.
_PASS_THROUGH = (
    "rule_id",
    "crr_tier",
    "scenario_weight",
    "priority_score",
    "triage_priority",
    "alert_ts",
    "content_hash",
    "first_seen_cycle",
    "first_seen_as_of",
    "in_current_detection",
    "generated_date",
)

# Row layouts shipped to the executors (tuples, not Rows, to keep the
# per-customer memory small).
_CUR_FIELDS = (
    "alert_id",
    "alert_key",
    "content_hash",
    "rule_id",
    "alert_ts",
    "generated_date",
    "truth",
    "triage_priority",
    "priority_score",
    "scenario_weight",
    "crr_tier",
)
_PRIOR_FIELDS = _CUR_FIELDS + ("first_seen_cycle", "first_seen_as_of")


def _simulate_group(item, params, as_of, prev_as_of, cycle):
    """RDD adapter: (customer_id, iterable of ("n"|"p", tuple)) -> tagged rows.

    Iterates the group once; the cap on alerts per customer is applied in
    Spark before this runs, so a hub customer's memory is bounded.
    """
    customer_id, rows = item
    current, prior = [], []
    crr_tier = None
    for tag, r in rows:
        if tag == "n":
            d = dict(zip(_CUR_FIELDS, r))  # noqa: B905
            crr_tier = d["crr_tier"]
            current.append(d)
        else:
            d = dict(zip(_PRIOR_FIELDS, r))  # noqa: B905
            if crr_tier is None:
                crr_tier = d["crr_tier"]
            prior.append(d)
    alerts = match_alerts(current, prior, prev_as_of, as_of, cycle)
    del current, prior
    disp, cases = simulate_customer(customer_id, crr_tier, alerts, params, as_of)
    truth = {a["alert_key"]: bool(a["truth"]) for a in alerts}
    out = []
    for d in disp:
        d["entity_id"] = customer_id
        d["simulated_truth"] = truth[d["alert_key"]]
        out.append(("d", json.dumps(_jsonable(d))))
    for c in cases:
        out.append(("c", json.dumps(_jsonable(c))))
    return out


def _jsonable(d):
    out = {}
    for k, v in d.items():
        if isinstance(v, date):
            out[k] = v.isoformat()
        else:
            out[k] = v
    return out


# ---------------------------------------------------------------------------
# Run identity
# ---------------------------------------------------------------------------

_CYCLE_SUFFIX = re.compile(r"^(?P<base>.+)-c(?P<n>\d+)$")


def split_run_id(run_id: str, cycle: int | None = None) -> tuple[str, int]:
    """(base run id, cycle number). Multi-cycle batch runs pass
    ``<run>-c<N>``; continuous passes the operations tick as ``cycle``."""
    m = _CYCLE_SUFFIX.match(run_id)
    if cycle is not None:
        return run_id, int(cycle)
    if m:
        return m.group("base"), int(m.group("n"))
    return run_id, 1


# ---------------------------------------------------------------------------
# Snapshots
# ---------------------------------------------------------------------------


def current_snapshot_id(spark, fq_table):
    """The table's newest snapshot id, or None (empty, or not Iceberg)."""
    try:
        rows = spark.sql(
            f"SELECT snapshot_id FROM {fq_table}.snapshots ORDER BY committed_at DESC LIMIT 1"
        ).collect()
    except Exception as e:  # noqa: BLE001
        log(f"[tm] snapshot of {fq_table} unavailable: {one_line(e)}")
        return None
    return int(rows[0][0]) if rows else None


def read_at_snapshot(spark, fq_table, snapshot_id):
    """The table as of one snapshot, so every action reads the same data."""
    if snapshot_id is None:
        return spark.table(fq_table)
    return spark.sql(f"SELECT * FROM {fq_table} VERSION AS OF {int(snapshot_id)}")


# ---------------------------------------------------------------------------
# Spark stages
# ---------------------------------------------------------------------------

# Raw source files already counted, by path (datagen files are immutable),
# so a continuous run reads only the footers of files new since its last
# operations pass. Driver-local; reset when a file disappears.
_SOURCE_SEEN = {"files": set(), "rows": 0}


def count_source_rows(spark):
    """Payments the datagen wrote (the raw pacs.008 Parquet), or None."""
    from bronze_verify_financial import BRONZE_URI, PACS_PREFIX

    try:
        files = set(spark.read.parquet(BRONZE_URI + PACS_PREFIX).inputFiles())
        if not _SOURCE_SEEN["files"] <= files:
            _SOURCE_SEEN["files"], _SOURCE_SEEN["rows"] = set(), 0
        new = sorted(files - _SOURCE_SEEN["files"])
        if new:
            _SOURCE_SEEN["rows"] += int(spark.read.parquet(*new).count())
            _SOURCE_SEEN["files"] |= set(new)
        return _SOURCE_SEEN["rows"]
    except Exception as e:  # noqa: BLE001
        log(f"[tm] source payment count unavailable: {one_line(e)}")
        return None


def classify_payments(txns, entities):
    """Monitored or excluded, per silver payment, plus DQ rule flags.

    A payment is monitored when either party is a customer of the reporting
    FI, unless its amount cannot be put in USD (no amount-based scenario can
    evaluate it). Order of the exclusion reasons: not our payment first. The
    customer-id set is broadcast (about 10 MB at scale 10), so the payments
    are scanned once with no shuffle.
    """
    from pyspark.sql.functions import broadcast, coalesce, col, lit, when

    cust = broadcast(entities.where(col("is_customer") == lit(True)).select("entity_id").distinct())
    o = cust.select(col("entity_id").alias("originator_id"), lit(True).alias("_o_cust"))
    b = cust.select(col("entity_id").alias("beneficiary_id"), lit(True).alias("_b_cust"))
    t = txns.select(
        "originator_id",
        "beneficiary_id",
        "txn_amount",
        "txn_amount_usd",
        "originator_bank_bic",
        "beneficiary_bank_bic",
    )
    t = t.join(broadcast(o), "originator_id", "left").join(broadcast(b), "beneficiary_id", "left")
    customer_party = coalesce(col("_o_cust"), lit(False)) | coalesce(col("_b_cust"), lit(False))
    return t.select(
        when(~customer_party, lit("no_customer_party"))
        .when(col("txn_amount_usd").isNull(), lit("dq_unconvertible_currency"))
        .otherwise(lit("monitored"))
        .alias("classification"),
        col("txn_amount_usd"),
        col("txn_amount_usd").isNull().alias("dq_unconvertible_currency"),
        (col("txn_amount") <= 0).alias("dq_nonpositive_amount"),
        (col("originator_id") == col("beneficiary_id")).alias("dq_self_transfer"),
        (col("originator_bank_bic").isNull() | col("beneficiary_bank_bic").isNull()).alias(
            "dq_missing_agent_bic"
        ),
    )


DQ_RULES = (
    "dq_unconvertible_currency",
    "dq_nonpositive_amount",
    "dq_self_transfer",
    "dq_missing_agent_bic",
)


def reconcile(spark, txns, entities, source_rows, bronze_rows, continuous):
    """Completeness rows (section, item, unit, count, amount) for one cycle."""
    from pyspark.sql.functions import col, count, lit, when
    from pyspark.sql.functions import sum as sum_

    cls = classify_payments(txns, entities)
    aggs = [count(lit(1)).alias("n"), sum_(col("txn_amount_usd")).alias("usd")]
    aggs += [sum_(when(col(r), lit(1)).otherwise(lit(0))).alias(r) for r in DQ_RULES]
    grouped = {r["classification"]: r for r in cls.groupBy("classification").agg(*aggs).collect()}
    customers = int(
        entities.where(col("is_customer") == lit(True)).select("entity_id").distinct().count()
    )

    def n(k):
        return int(grouped[k]["n"]) if k in grouped else 0

    def usd(k):
        return grouped[k]["usd"] if k in grouped else None

    silver_rows = sum(int(r["n"]) for r in grouped.values())
    rows = [
        ("completeness", "customers", "entities", customers, None),
        ("completeness", "source", "payments", source_rows, None),
        ("completeness", "bronze", "payments", bronze_rows, None),
        ("completeness", "silver", "payments", silver_rows, None),
        ("completeness", "monitored", "payments", n("monitored"), usd("monitored")),
    ]
    excluded = 0
    for reason in ("no_customer_party", "dq_unconvertible_currency"):
        rows.append(("exclusion", reason, "payments", n(reason), usd(reason)))
        excluded += n(reason)
    if continuous and source_rows is not None:
        # Written by datagen, not yet carried into silver by the stream.
        # Silver was pinned before the source was counted, so this cannot
        # go negative unless silver holds rows the source never had.
        in_flight = source_rows - silver_rows
        rows.append(("exclusion", "in_flight", "payments", in_flight, None))
        excluded += in_flight
    rows.append(("completeness", "excluded", "payments", excluded, None))
    for rule in DQ_RULES:
        rows.append(
            ("dq", rule, "payments", sum(int(r[rule] or 0) for r in grouped.values()), None)
        )
    return rows, {"monitored": n("monitored"), "excluded": excluded, "silver": silver_rows}


def build_alert_inputs(spark, alerts, entities, manifest, params, known=None):
    """One row per alert: content key, customer flags, truth and priority,
    and the per-customer rank the capacity cap reads."""
    from pyspark.sql.functions import (
        array,
        array_sort,
        coalesce,
        col,
        concat_ws,
        create_map,
        date_add,
        explode,
        lit,
        row_number,
        sha2,
        to_date,
        when,
    )
    from pyspark.sql.window import Window

    weight_map = create_map(*[x for k, v in SCENARIO_WEIGHT.items() for x in (lit(k), lit(v))])
    crr_map = create_map(*[x for k, v in CRR_MULTIPLIER.items() for x in (lit(k), lit(v))])
    declared = list(params.get("counterparty_scenarios") or ())
    ents = entities.select(
        col("entity_id"),
        coalesce(col("is_customer"), lit(False)).alias("is_customer"),
        col("crr_tier"),
    ).dropDuplicates(["entity_id"])
    content = sha2(
        concat_ws(
            "|",
            col("rule_id"),
            col("entity_id").cast("string"),
            col("alert_ts").cast("string"),
            concat_ws(
                ",", array_sort(coalesce(col("related_txn_ids"), array().cast("array<string>")))
            ),
        ),
        256,
    )
    raw = alerts.select("alert_id", "rule_id", "entity_id", "alert_ts", "related_txn_ids")
    planted = (
        manifest.where(col("typology_type") != lit("random"))
        .select(explode(col("participant_uetrs")).alias("uetr"))
        .distinct()
    )
    hits = (
        raw.select("alert_id", explode(col("related_txn_ids")).alias("uetr"))
        .join(planted, "uetr", "left_semi")
        .select("alert_id")
        .distinct()
        .withColumn("_hit", lit(True))
    )
    # related_txn_ids is dropped here, before the window shuffle below: a W1
    # alert can carry 250K ids.
    base = raw.select("alert_id", "rule_id", "entity_id", "alert_ts", content.alias("content_hash"))
    # Identical alerts (same rule, entity, time and txns) share a content
    # hash; the occurrence number keeps their keys distinct.
    w = Window.partitionBy("content_hash").orderBy("alert_id")
    base = base.withColumn(
        "alert_key",
        concat_ws("-", col("content_hash"), (row_number().over(w) - 1).cast("string")),
    )
    out = (
        base.join(hits, "alert_id", "left")
        .join(ents, "entity_id", "left")
        .select(
            "alert_id",
            "alert_key",
            "content_hash",
            "rule_id",
            "entity_id",
            "alert_ts",
            coalesce(col("is_customer"), lit(False)).alias("is_customer"),
            col("rule_id").isin(declared).alias("declared_counterparty")
            if declared
            else lit(False).alias("declared_counterparty"),
            col("crr_tier"),
            coalesce(weight_map[col("rule_id")], lit(DEFAULT_SCENARIO_WEIGHT)).alias(
                "scenario_weight"
            ),
            date_add(to_date(col("alert_ts")), 1).alias("generated_date"),
            coalesce(col("_hit"), lit(False)).alias("simulated_truth"),
        )
        .withColumn(
            "priority_score",
            col("scenario_weight") * coalesce(crr_map[col("crr_tier")], lit(1.0)),
        )
    )
    band = None
    for floor, name in PRIORITY_BANDS:
        cond = col("priority_score") >= lit(floor)
        band = when(cond, lit(name)) if band is None else band.when(cond, lit(name))
    out = out.withColumn("triage_priority", band.otherwise(lit("low")))
    cap = int(params.get("max_alerts_per_customer") or 0)
    if cap <= 0:
        return out.withColumn("over_capacity", lit(False))
    # Alerts already in the workflow (same content as a carried prior alert)
    # are never capped: capping one would drop it from the replay while its
    # prior row is carried, writing the alert twice. Only new alerts are
    # ranked against the cap.
    if known is not None:
        k = known.select("entity_id", "content_hash").distinct().withColumn("_known", lit(True))
        out = out.join(k, ["entity_id", "content_hash"], "left")
    else:
        out = out.withColumn("_known", lit(None).cast("boolean"))
    new = col("_known").isNull()
    rank = Window.partitionBy("entity_id", new).orderBy("generated_date", "alert_key")
    over = col("is_customer") & new & (row_number().over(rank) > lit(cap))
    return out.withColumn("over_capacity", over).drop("_known")


_DISP_SIM_SCHEMA = (
    "alert_id STRING, alert_key STRING, entity_id BIGINT, rule_id STRING, crr_tier STRING, "
    "scenario_weight DOUBLE, priority_score DOUBLE, triage_priority STRING, "
    "alert_ts BIGINT, content_hash STRING, first_seen_cycle INT, first_seen_as_of DATE, "
    "in_current_detection BOOLEAN, generated_date DATE, l1_decision_date DATE, "
    "disposition STRING, queue_status STRING, case_id STRING, decision_date DATE, "
    "aging_days INT, sla_breached BOOLEAN, simulated_truth BOOLEAN, analyst_correct BOOLEAN, "
    "qa_sampled BOOLEAN, qa_disposition STRING, qa_disagrees BOOLEAN"
)
_CASE_SCHEMA = (
    "case_id STRING, customer_id BIGINT, case_type STRING, parent_case_id STRING, "
    "opened_date DATE, crr_tier STRING, priority STRING, alert_count INT, "
    "escalated_alert_count INT, rule_ids ARRAY<STRING>, first_alert_date DATE, "
    "activity_window_start DATE, activity_window_end DATE, case_status STRING, "
    "determination STRING, determination_date DATE, sar_decision STRING, "
    "suspect_identified BOOLEAN, regulatory_limit STRING, filing_deadline_date DATE, "
    "filing_date DATE, determination_to_filing_days INT, days_since_prior_sar INT, "
    "filed_late BOOLEAN, alert_to_decision_days INT, sla_breached BOOLEAN, "
    "continuing_review_due_date DATE, continuing_review_status STRING, "
    "continuing_review_case_id STRING, simulated_truth BOOLEAN"
)


def _replay_col(name):
    from pyspark.sql.functions import col, unix_micros

    if name == "truth":
        return col("simulated_truth")
    if name == "alert_ts":
        return unix_micros(col("alert_ts")).alias("alert_ts")
    return col(name)


def simulate(spark, inputs, prior, params, as_of, prev_as_of, cycle):
    """Replay every customer's alerts. Returns (dispositions, cases, tagged);
    the caller unpersists ``tagged``."""
    import functools

    from pyspark import StorageLevel
    from pyspark.sql.functions import col, from_json, lit

    cur = inputs.where(col("is_customer") & ~col("over_capacity")).select(
        "entity_id", *[_replay_col(f) for f in _CUR_FIELDS]
    )
    rdd = cur.rdd.map(lambda r: (r[0], ("n", tuple(r[1:]))))
    if prior is not None:
        p = prior.select("entity_id", *[_replay_col(f) for f in _PRIOR_FIELDS])
        rdd = rdd.union(p.rdd.map(lambda r: (r[0], ("p", tuple(r[1:])))))
    fn = functools.partial(
        _simulate_group, params=dict(params), as_of=as_of, prev_as_of=prev_as_of, cycle=cycle
    )
    tagged = spark.createDataFrame(rdd.groupByKey().flatMap(fn), "tag STRING, payload STRING")
    tagged = tagged.persist(StorageLevel.MEMORY_AND_DISK)
    disp = tagged.where(col("tag") == lit("d")).select(
        from_json(col("payload"), _DISP_SIM_SCHEMA).alias("r")
    )
    cases = tagged.where(col("tag") == lit("c")).select(
        from_json(col("payload"), _CASE_SCHEMA).alias("r")
    )
    return disp.select("r.*"), cases.select("r.*"), tagged


def case_activity(txns, cases):
    """Payments in each case's lookback window, both sides of the customer,
    in one scan of the payments (each payment exploded to its distinct
    parties and joined to the broadcast case windows)."""
    from pyspark.sql.functions import (
        array,
        array_distinct,
        broadcast,
        col,
        count,
        explode,
        lit,
        to_date,
    )
    from pyspark.sql.functions import sum as sum_

    win = cases.select("case_id", "customer_id", "activity_window_start", "activity_window_end")
    t = txns.select(
        explode(array_distinct(array(col("originator_id"), col("beneficiary_id")))).alias("_party"),
        to_date(col("txn_timestamp")).alias("_d"),
        "txn_amount_usd",
    )
    j = t.join(broadcast(win), t["_party"] == win["customer_id"]).where(
        (col("_d") >= col("activity_window_start")) & (col("_d") < col("activity_window_end"))
    )
    return j.groupBy("case_id").agg(
        count(lit(1)).alias("activity_txn_count"),
        sum_(col("txn_amount_usd")).cast("decimal(38,2)").alias("activity_amount_usd"),
    )


def coverage_rows(spark, inputs, status_rows, manifest, rule_targets):
    """Scenario-to-typology matrix: designed coverage, this cycle's rule
    status and alert volume, and planted typologies no scenario covers."""
    from pyspark.sql.functions import col, count, lit, when
    from pyspark.sql.functions import sum as sum_

    counts = {
        r["rule_id"]: (int(r["n"]), int(r["c"]))
        for r in inputs.groupBy("rule_id")
        .agg(
            count(lit(1)).alias("n"),
            sum_(when(col("is_customer"), lit(1)).otherwise(lit(0))).alias("c"),
        )
        .collect()
    }
    planted = {}
    if manifest is not None:
        planted = {
            r["typology_type"]: int(r["n"])
            for r in manifest.groupBy("typology_type").agg(count(lit(1)).alias("n")).collect()
        }
    status = {r["rule_id"]: r["status"] for r in status_rows}
    rows = []
    rules = list(rule_targets) + sorted(set(status) - set(rule_targets))
    for rid in rules:
        typ = rule_targets.get(rid)
        n, c = counts.get(rid, (0, 0))
        rows.append(
            (
                typ,
                rid,
                "designated" if typ else "attribute",
                status.get(rid, "not_configured"),
                n,
                c,
                planted.get(typ) if typ else None,
            )
        )
    covered = {t for t in rule_targets.values() if t}
    for typ in sorted(set(planted) - covered - {"random"}):
        rows.append((typ, None, "gap", None, None, None, planted[typ]))
    return rows


# ---------------------------------------------------------------------------
# Invariants (P10.2), evaluated on the written tables
# ---------------------------------------------------------------------------


def evaluate_invariants(counts: dict) -> list[tuple[str, str, str]]:
    """``counts`` from :func:`read_back`. Returns (name, status, detail)."""
    out = []

    def check(name, ok, detail):
        out.append((name, "pass" if ok else "fail", detail))

    custs = counts.get("customers")
    check(
        "monitored_population",
        bool(custs) and counts["monitored"] > 0,
        f"{custs} customers of the reporting FI, {counts['monitored']} monitored payments",
    )
    src = counts.get("source")
    mon, exc = counts["monitored"], counts["excluded"]
    if src is None:
        out.append(
            (
                "reconciliation",
                "unchecked",
                "source payment count unavailable (listing the raw files failed); "
                "completeness unproven",
            )
        )
    else:
        # A negative item (silver holding more than the source, so in_flight
        # below zero) is a duplication, not a balanced ledger.
        neg = counts.get("negative_items") or []
        check(
            "reconciliation",
            mon + exc == src and not neg,
            f"monitored {mon} + excluded {exc} = {mon + exc} vs source {src}"
            + (f"; negative: {', '.join(neg)}" if neg else ""),
        )
    alerts, disp = counts["alerts"], counts["dispositions"]
    check(
        "every_alert_dispositioned",
        alerts == disp,
        f"alerts {alerts}, disposition rows for them {disp}",
    )
    rows, keys = counts.get("disposition_rows"), counts.get("distinct_alert_keys")
    if rows is not None and keys is not None:
        check(
            "one_row_per_alert_identity",
            rows == keys,
            f"{rows} disposition rows, {keys} distinct alert identities",
        )
    nulls = counts.get("null_dispositions", 0)
    check("no_null_disposition", nulls == 0, f"{nulls} disposition rows with no disposition")
    und = counts.get("noncustomer_undeclared", 0)
    check(
        "noncustomer_alerts_declared",
        und == 0,
        f"{und} alerts on non-customers from scenarios not declared customer-and-counterparty"
        f" ({counts.get('noncustomer_alerts', 0)} non-customer alerts in all)",
    )
    ca, esc = counts["customer_alerts"], counts["escalated"]
    check("escalated_le_alerts", esc <= ca, f"escalated {esc} <= customer alerts {ca}")
    ac = counts["alert_cases"]
    check("cases_le_escalated", ac <= esc, f"alert-driven cases {ac} <= escalated {esc}")
    sars, cases = counts["sars"], counts["cases"]
    check("sars_le_cases", sars <= cases, f"SARs {sars} <= cases {cases}")
    mo = counts["max_open_per_customer"]
    check("one_open_case_per_customer", mo <= 1, f"most open cases on one customer: {mo}")
    funnel = [
        ("payments", src if src is not None else counts["silver"]),
        ("monitored", mon),
        ("alerts", ca),
        ("escalated", esc),
        ("cases", ac),
        ("sars", counts["alert_sars"]),
    ]
    # No zip(strict=...): the Spark image runs Python 3.9.
    bad = [
        f"{funnel[i][0]}={funnel[i][1]} < {funnel[i + 1][0]}={funnel[i + 1][1]}"
        for i in range(len(funnel) - 1)
        if funnel[i + 1][1] > funnel[i][1]
    ]
    check(
        "funnel_monotone",
        not bad,
        "; ".join(bad) or " >= ".join(f"{k} {v}" for k, v in funnel),
    )
    miss = counts["reviews_missing"]
    check(
        "continuing_review_fires",
        miss == 0,
        f"{miss} SARs past their 90-day review date with no review "
        f"({counts['reviews_due']} due, {counts.get('reviews_deferred', 0)} deferred behind "
        "a case waiting to file)",
    )
    folded = counts.get("reviews_folded_into_determined", 0)
    check(
        "review_not_folded_into_determined",
        folded == 0,
        f"{folded} reviews credited to a case already determined before the review was due",
    )
    if counts.get("history_checked"):
        changed = counts.get("history_changed", 0)
        check(
            "history_stable",
            changed == 0,
            f"{changed} decisions made by {counts.get('prev_as_of')} differ from the previous "
            f"cycle ({counts.get('history_compared', 0)} compared)",
        )
    return out


def _flag(c):
    from pyspark.sql.functions import lit, when

    return when(c, lit(1)).otherwise(lit(0))


def read_back(
    spark, run_id, as_of, prior_disp=None, prior_cases=None, prev_as_of=None, rerun=False
):
    """Everything the invariants, the funnel rows and the operations summary
    need, from the written tables in a handful of actions: one grouped
    collect per table, the open-case maximum, the folded-review check, and
    the history comparison when there is a previous cycle."""
    from pyspark.sql.functions import broadcast, col, count, lit, when
    from pyspark.sql.functions import max as max_

    d = spark.table(f"{CATALOG}.{GOLD_DISPOSITIONS}").where(col("run_id") == lit(run_id))
    cases = spark.table(f"{CATALOG}.{GOLD_CASES}").where(col("run_id") == lit(run_id))
    sar_cases = cases.where(col("sar_decision") == lit("sar_filed")).select(
        "case_id", lit(True).alias("_sar")
    )
    bucket = None
    for lo, hi, name in AGING_BUCKETS:
        cond = col("aging_days") >= lit(lo)
        if hi is not None:
            cond = cond & (col("aging_days") <= lit(hi))
        bucket = when(cond, lit(name)) if bucket is None else bucket.when(cond, lit(name))
    dg = (
        d.join(broadcast(sar_cases), "case_id", "left")
        .groupBy(
            "rule_id",
            "is_customer",
            "declared_counterparty",
            "in_current_detection",
            "disposition",
            "queue_status",
            "triage_priority",
            bucket.otherwise(lit("0-30")).alias("aging_bucket"),
            "sla_breached",
            col("l1_decision_date").isNotNull().alias("l1_decided"),
            col("decision_date").isNotNull().alias("decided"),
            col("_sar").isNotNull().alias("on_sar"),
            "qa_sampled",
            "qa_disagrees",
        )
        .agg(count(lit(1)).alias("n"))
        .collect()
    )
    cg = (
        cases.groupBy(
            "case_type",
            "case_status",
            "sar_decision",
            "suspect_identified",
            "regulatory_limit",
            "filed_late",
            "continuing_review_status",
            (col("continuing_review_due_date") <= lit(as_of)).alias("review_due"),
            col("continuing_review_case_id").isNull().alias("review_missing"),
            (col("opened_date") <= lit(as_of - timedelta(days=60))).alias("opened_60"),
            "determination_to_filing_days",
            (col("days_since_prior_sar") > lit(CONTINUING_FILING_LIMIT_DAYS)).alias("over_120"),
        )
        .agg(count(lit(1)).alias("n"))
        .collect()
    )
    mo = (
        cases.where(col("case_status") != lit("closed"))
        .groupBy("customer_id")
        .count()
        .agg(max_("count").alias("m"))
        .collect()[0]["m"]
    )
    # A folded review is credited to a case that was still undetermined when
    # the review fell due.
    parents = cases.where(col("continuing_review_status") == lit("folded")).select(
        col("continuing_review_case_id").alias("case_id"),
        col("continuing_review_due_date").alias("_due"),
    )
    folded_bad = (
        parents.join(cases.select("case_id", "determination_date"), "case_id", "left")
        .where(col("determination_date").isNotNull() & (col("determination_date") < col("_due")))
        .count()
    )
    alerts = spark.table(f"{CATALOG}.{GOLD_ALERTS}").where(col("run_id") == lit(run_id)).count()
    distinct_keys = d.select("alert_key").distinct().count()

    def s(rows, pred):
        return sum(int(r["n"]) for r in rows if pred(r))

    cust = [r for r in dg if r["is_customer"]]
    c_alert = [r for r in cg if r["case_type"] == "alert_escalation"]
    sar = [r for r in cg if r["sar_decision"] == "sar_filed"]
    counts = {
        "alerts": int(alerts),
        "dispositions": s(dg, lambda r: r["in_current_detection"]),
        "disposition_rows": s(dg, lambda r: True),
        "distinct_alert_keys": int(distinct_keys),
        "null_dispositions": s(dg, lambda r: r["disposition"] is None),
        "noncustomer_alerts": s(dg, lambda r: not r["is_customer"]),
        "noncustomer_undeclared": s(
            dg, lambda r: not r["is_customer"] and not r["declared_counterparty"]
        ),
        "withdrawn_alerts": s(dg, lambda r: not r["in_current_detection"]),
        "over_capacity": s(dg, lambda r: r["disposition"] == DISP_OVER_CAPACITY),
        "customer_alerts": s(cust, lambda r: True),
        "escalated": s(cust, lambda r: r["disposition"] == DISP_ESCALATED),
        "cases": s(cg, lambda r: True),
        "alert_cases": s(c_alert, lambda r: True),
        "review_cases": s(cg, lambda r: r["case_type"] != "alert_escalation"),
        "sars": s(sar, lambda r: True),
        "alert_sars": s(sar, lambda r: r["case_type"] == "alert_escalation"),
        "review_sars": s(sar, lambda r: r["case_type"] != "alert_escalation"),
        "max_open_per_customer": int(mo or 0),
        "reviews_due": s(sar, lambda r: bool(r["review_due"])),
        "reviews_missing": s(
            sar,
            lambda r: (
                bool(r["review_due"])
                and r["review_missing"]
                and r["continuing_review_status"] != "deferred"
            ),
        ),
        "reviews_deferred": s(sar, lambda r: r["continuing_review_status"] == "deferred"),
        "reviews_superseded": s(
            sar, lambda r: r["continuing_review_status"] == "superseded_by_sar"
        ),
        "reviews_opened": s(sar, lambda r: r["continuing_review_status"] == "opened"),
        "reviews_folded": s(sar, lambda r: r["continuing_review_status"] == "folded"),
        "reviews_folded_into_determined": int(folded_bad),
        "_dg": dg,
        "_cg": cg,
    }
    counts.update(
        _history_check(spark, run_id, prior_disp, prior_cases, prev_as_of, rerun)
        if prior_disp is not None and prev_as_of is not None
        else {"history_checked": False}
    )
    return counts


def _history_check(spark, run_id, prior_disp, prior_cases, prev_as_of, rerun=False):
    """Decisions made by the previous as-of date, compared with this cycle's
    tables: a changed disposition, case, decision date, determination or
    filing is history rewritten."""
    from pyspark.sql.functions import coalesce, col, lit

    same = lambda a, b: coalesce(col(a) == col(b), col(a).isNull() & col(b).isNull())  # noqa: E731
    prev = lit(prev_as_of)
    worked = col("disposition").isin(*WORKED_DISPOSITIONS)
    if rerun:
        # A rerun's prior tables also hold decisions made after the previous
        # as-of date, which may legitimately differ: compare only decisions
        # dated by then (an undated attachment is not compared).
        worked = worked & ((col("decision_date") <= prev) | (col("l1_decision_date") <= prev))
    pd_ = prior_disp.where(worked).select(
        "alert_key",
        col("disposition").alias("p_disp"),
        col("case_id").alias("p_case"),
        col("decision_date").alias("p_dec"),
    )
    nd = spark.table(f"{CATALOG}.{GOLD_DISPOSITIONS}").where(col("run_id") == lit(run_id))
    nd = nd.select(
        "alert_key",
        col("disposition").alias("n_disp"),
        col("case_id").alias("n_case"),
        col("decision_date").alias("n_dec"),
        lit(True).alias("_present"),
    )
    j = pd_.join(nd, "alert_key", "left")
    changed_d = ~(
        col("_present").isNotNull()
        & same("p_disp", "n_disp")
        & same("p_case", "n_case")
        & (col("p_dec").isNull() | (col("p_dec") > prev) | same("p_dec", "n_dec"))
    )
    dc = j.select(_flag(changed_d).alias("c")).groupBy().sum("c").collect()[0][0] or 0
    dn = pd_.count()
    cn = cc = 0
    if prior_cases is not None:
        pc = prior_cases.where(col("opened_date") <= prev).select(
            "case_id",
            col("determination").alias("p_det"),
            col("determination_date").alias("p_dd"),
            col("sar_decision").alias("p_sar"),
            col("filing_date").alias("p_fd"),
        )
        nc = spark.table(f"{CATALOG}.{GOLD_CASES}").where(col("run_id") == lit(run_id))
        nc = nc.select(
            "case_id",
            col("determination").alias("n_det"),
            col("determination_date").alias("n_dd"),
            col("sar_decision").alias("n_sar"),
            col("filing_date").alias("n_fd"),
            lit(True).alias("_present"),
        )
        jc = pc.join(nc, "case_id", "left")
        changed_c = ~(
            col("_present").isNotNull()
            & (
                col("p_dd").isNull()
                | (col("p_dd") > prev)
                | (same("p_det", "n_det") & same("p_dd", "n_dd"))
            )
            & (
                col("p_fd").isNull()
                | (col("p_fd") > prev)
                | (same("p_sar", "n_sar") & same("p_fd", "n_fd"))
            )
        )
        cc = jc.select(_flag(changed_c).alias("c")).groupBy().sum("c").collect()[0][0] or 0
        cn = pc.count()
    return {
        "history_checked": True,
        "history_changed": int(dc) + int(cc),
        "history_compared": int(dn) + int(cn),
        "prev_as_of": prev_as_of.isoformat(),
    }


# ---------------------------------------------------------------------------
# Operations summary (P10.3 / P10.4 vocabulary)
# ---------------------------------------------------------------------------


def ops_summary(as_of, params, recon_rows, counts):
    """The operations pack, computed from the grouped rows read_back
    collected (no further Spark actions)."""
    dg = [r for r in counts["_dg"] if r["is_customer"]]
    cg = counts["_cg"]

    def s(rows, pred):
        return sum(int(r["n"]) for r in rows if pred(r))

    def decided(r):
        return r["disposition"] in WORKED_DISPOSITIONS and r["decided"]

    per_rule = {}
    for rid in sorted({r["rule_id"] for r in dg}):
        rr = [r for r in dg if r["rule_id"] == rid]
        n = s(rr, lambda r: True)
        dec = s(rr, decided)
        prod = s(rr, lambda r: decided(r) and (r["disposition"] == DISP_ESCALATED or r["on_sar"]))
        per_rule[rid] = {
            "alerts": n,
            "escalated": s(rr, lambda r: r["disposition"] == DISP_ESCALATED),
            "productive_rate": (prod / dec) if dec else None,
            "sar_conversion": (s(rr, lambda r: r["on_sar"]) / n) if n else None,
        }
    aging = {name: 0 for _, _, name in AGING_BUCKETS}
    for r in counts["_dg"]:
        if r["queue_status"] == "open":
            aging[r["aging_bucket"]] += int(r["n"])
    l1 = [r for r in dg if r["l1_decided"]]
    n_l1 = s(l1, lambda r: True)
    n_qa = s(l1, lambda r: r["qa_sampled"])
    by_priority = {}
    for r in dg:
        by_priority[r["triage_priority"]] = by_priority.get(r["triage_priority"], 0) + int(r["n"])
    by_disp = {}
    for r in counts["_dg"]:
        by_disp[r["disposition"]] = by_disp.get(r["disposition"], 0) + int(r["n"])
    filing = []
    for r in cg:
        if r["determination_to_filing_days"] is not None:
            filing.extend([int(r["determination_to_filing_days"])] * int(r["n"]))
    filing.sort()
    by_status, by_type, by_limit = {}, {}, {}
    for r in cg:
        by_status[r["case_status"]] = by_status.get(r["case_status"], 0) + int(r["n"])
        by_type[r["case_type"]] = by_type.get(r["case_type"], 0) + int(r["n"])
    sar = [r for r in cg if r["sar_decision"] == "sar_filed"]
    for r in sar:
        k = r["regulatory_limit"] or "unknown"
        cur = by_limit.setdefault(k, {"filed": 0, "late": 0})
        cur["filed"] += int(r["n"])
        cur["late"] += int(r["n"]) if r["filed_late"] else 0

    def pct(xs, q):
        if not xs:
            return None
        return xs[min(len(xs) - 1, int(q * (len(xs) - 1) + 0.5))]

    sim_keys = [k for k in sorted(params) if k != "counterparty_scenarios"]
    return {
        "as_of_date": as_of.isoformat(),
        "simulation": {
            "note": "dispositions simulated from datagen ground truth",
            **{k: params[k] for k in sim_keys},
            "counterparty_scenarios": list(params.get("counterparty_scenarios") or ()),
        },
        "reconciliation": {f"{s_}.{i}": v for s_, i, _, v, _ in recon_rows},
        "funnel": {
            "payments": counts["source"],
            "monitored": counts["monitored"],
            "alerts": counts["customer_alerts"],
            "escalated": counts["escalated"],
            "cases": counts["alert_cases"],
            "sars": counts["alert_sars"],
        },
        "alerts_total": counts["alerts"],
        "alerts_out_of_scope": counts["noncustomer_alerts"],
        "alerts_noncustomer_undeclared": counts["noncustomer_undeclared"],
        "alerts_withdrawn_carried": counts["withdrawn_alerts"],
        "alerts_over_capacity": counts["over_capacity"],
        "alerts_by_disposition": by_disp,
        "l1_decided": n_l1,
        "l1_escalation_rate": (
            s(l1, lambda r: r["disposition"] == DISP_ESCALATED) / n_l1 if n_l1 else None
        ),
        "alert_sla_breaches": s(l1, lambda r: r["sla_breached"]),
        "qa_sample": n_qa,
        "qa_disagreement_rate": (s(l1, lambda r: bool(r["qa_disagrees"])) / n_qa) if n_qa else None,
        "alerts_by_priority": by_priority,
        "alert_aging_open": aging,
        "cases_by_status": by_status,
        "cases_by_type": by_type,
        "open_cases": counts["cases"] - by_status.get("closed", 0),
        "open_cases_over_60_days": s(
            cg, lambda r: r["case_status"] != "closed" and bool(r["opened_60"])
        ),
        "sars_filed": counts["sars"],
        "sars_by_limit": by_limit,
        "sars_no_suspect": s(sar, lambda r: r["suspect_identified"] is False),
        "continuing_sars_over_120_days": s(sar, lambda r: bool(r["over_120"])),
        "filing_days_median": pct(filing, 0.5),
        "filing_days_p95": pct(filing, 0.95),
        "filed_over_30_days_pct": (
            (sum(1 for x in filing if x > FILING_DEADLINE_DAYS) / len(filing)) if filing else None
        ),
        "filed_late": s(sar, lambda r: bool(r["filed_late"])),
        "continuing_reviews_due": counts["reviews_due"],
        "continuing_reviews_opened": counts["reviews_opened"],
        "continuing_reviews_folded": counts["reviews_folded"],
        "continuing_reviews_deferred": counts["reviews_deferred"],
        "continuing_reviews_superseded": counts["reviews_superseded"],
        "scenarios": per_rule,
    }


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def _read_manifest(spark):
    try:
        return spark.table(f"{CATALOG}.{MANIFEST_TABLE}")
    except Exception as e:  # noqa: BLE001
        log(f"[tm] manifest {MANIFEST_TABLE} not readable: {one_line(e)}")
        return None


def _write_recon(spark, rows, base_run_id, cycle, cycle_run_id, as_of):
    from decimal import Decimal

    from pyspark.sql.functions import current_timestamp, lit

    schema = "section STRING, item STRING, unit STRING, item_count BIGINT, amount_usd DECIMAL(38,2)"
    data = [
        (
            s,
            i,
            u,
            int(c) if c is not None else None,
            Decimal(str(a)).quantize(Decimal("0.01")) if a is not None else None,
        )
        for s, i, u, c, a in rows
    ]
    df = spark.createDataFrame(data, schema).select(
        lit(base_run_id).alias("run_id"),
        lit(cycle).cast("int").alias("cycle"),
        lit(cycle_run_id).alias("cycle_run_id"),
        lit(as_of).cast("date").alias("as_of_date"),
        "section",
        "item",
        "unit",
        "item_count",
        "amount_usd",
        current_timestamp().alias("computed_ts"),
    )
    t = f"{CATALOG}.{GOLD_RECON}"
    # This run's history only, one set of rows per cycle or tick; a rerun of
    # the same cycle replaces its own rows.
    safe_run = base_run_id.replace("'", "''")
    spark.sql(f"DELETE FROM {t} WHERE run_id <> '{safe_run}' OR cycle = {int(cycle)}")
    df.writeTo(t).append()


def _ledger_cycles(spark, base_run_id):
    """{cycle: as_of_date} already in the ledger for this run."""
    from pyspark.sql.functions import col, lit
    from pyspark.sql.functions import max as max_

    try:
        return {
            int(r["cycle"]): r["a"]
            for r in spark.table(f"{CATALOG}.{GOLD_RECON}")
            .where(col("run_id") == lit(base_run_id))
            .groupBy("cycle")
            .agg(max_("as_of_date").alias("a"))
            .collect()
        }
    except Exception as e:  # noqa: BLE001
        log(f"[tm] ledger unreadable: {one_line(e)}")
        return {}


def _prior_state(spark, base_run_id, cycle, ledger):
    """The previous cycle's dispositions and cases (pinned snapshots) to
    carry forward, its as-of date, and whether this is a rerun of the same
    cycle. (None, None, None, False) on a first cycle or another run's
    tables."""
    from pyspark.sql.functions import col, lit
    from pyspark.sql.functions import max as max_
    from pyspark.sql.functions import min as min_

    dt, ct = f"{CATALOG}.{GOLD_DISPOSITIONS}", f"{CATALOG}.{GOLD_CASES}"
    dsid, csid = current_snapshot_id(spark, dt), current_snapshot_id(spark, ct)
    if dsid is None:
        return None, None, None, False
    pdisp = read_at_snapshot(spark, dt, dsid)
    pcases = read_at_snapshot(spark, ct, csid) if csid is not None else None
    meta = pdisp.agg(
        min_("base_run_id").alias("lo"),
        max_("base_run_id").alias("hi"),
        max_("cycle").alias("c"),
        max_("as_of_date").alias("a"),
    ).collect()[0]
    if meta["lo"] is None or meta["lo"] != base_run_id or meta["hi"] != base_run_id:
        return None, None, None, False
    prior_cycle = int(meta["c"])
    if prior_cycle < cycle:
        prev_as_of = meta["a"]
    elif prior_cycle == cycle:
        # A rerun of this cycle: carry only what earlier cycles saw, dated by
        # the ledger's previous cycle.
        earlier = [c for c in ledger if c < cycle]
        if not earlier:
            return None, None, None, False
        prev_as_of = ledger[max(earlier)]
        pdisp = pdisp.where(col("first_seen_cycle") < lit(cycle))
        if pcases is not None:
            pcases = pcases.where(col("opened_date") <= lit(prev_as_of))
    else:
        return None, None, None, False
    if prev_as_of is None:
        return None, None, None, False
    return pdisp, pcases, prev_as_of, prior_cycle == cycle


def _status(status, cycle, reason):
    log(f"[tm-status] status={status} cycle={cycle} reason={one_line(reason, limit=400)}")


def run_tm_operations(
    spark,
    txns,
    run_id,
    *,
    cycle=None,
    continuous=False,
    params=None,
    source_rows_fn=None,
    rule_targets=None,
    txns_table=None,
):
    """Stages 1, 6, 7 and 8 for one cycle, then the invariant check.

    Never raises. Returns the list of (name, status, detail) invariants, or a
    single ``workflow`` entry with status ``not_run`` or ``disabled`` (with
    the reason) when the layer did not run. ``txns`` is only a fallback: the
    silver table (``txns_table``) is read at one pinned snapshot.
    """
    from pyspark.sql.functions import col, current_timestamp, lit, timestamp_micros
    from pyspark.sql.functions import max as max_

    params = dict(params or params_from_env())
    params.setdefault("counterparty_scenarios", DEFAULT_COUNTERPARTY_SCENARIOS)
    base_run_id, cycle_no = split_run_id(run_id, cycle)
    if not params.get("enabled", True):
        reason = "workload.tm_operations.enabled is false"
        try:
            # Empty tables, so readers (the investigator queries) still resolve.
            bootstrap_tm_tables(spark)
        except Exception as e:  # noqa: BLE001
            log(f"[tm] bootstrap skipped: {one_line(e)}")
        _status("disabled", cycle_no, reason)
        return [("workflow", "disabled", reason)]
    import time

    started = time.time()
    held = []
    try:
        if rule_targets is None:
            from detection_rules import RULE_TARGET_TYPOLOGY

            rule_targets = dict(RULE_TARGET_TYPOLOGY)
        bootstrap_tm_tables(spark)
        ledger = _ledger_cycles(spark, base_run_id)
        tick = None
        if continuous:
            # One ledger set per operations pass, numbered from the ledger so a
            # restarted gold-refresh driver appends instead of overwriting.
            tick = cycle_no
            cycle_no = max(ledger, default=0) + 1
            cycle_run_id = f"{run_id}-t{cycle_no}"
        else:
            cycle_run_id = run_id

        # Silver at one snapshot, pinned BEFORE the source is counted: every
        # payment in it was written by datagen before the count started.
        table = f"{CATALOG}.{txns_table or SILVER_TXNS}"
        sid = current_snapshot_id(spark, table)
        if sid is not None:
            txns = read_at_snapshot(spark, table, sid)
        else:
            log(f"[tm] {table} has no snapshot to pin; reading the frame as passed")
        newest = txns.agg(max_(col("txn_timestamp")).alias("m")).collect()[0]["m"]
        if newest is None:
            reason = f"{table} is empty; nothing to monitor"
            _status("not_run", cycle_no, reason)
            return [("workflow", "not_run", reason)]
        as_of = newest.date() + timedelta(days=1)
        entities = spark.table(f"{CATALOG}.{SILVER_ENTITIES}")
        manifest = _read_manifest(spark)
        if manifest is None:
            reason = (
                f"no ground-truth manifest ({MANIFEST_TABLE}); dispositions cannot be simulated"
            )
            _status("not_run", cycle_no, reason)
            return [("workflow", "not_run", reason)]

        # Stage 1: completeness.
        source_rows = (source_rows_fn or count_source_rows)(spark)
        bronze_rows, _ = iceberg_table_stats(spark, f"{CATALOG}.{BRONZE_TABLE}")
        recon_rows, recon = reconcile(spark, txns, entities, source_rows, bronze_rows, continuous)

        # The previous cycle, pinned before this cycle overwrites it.
        prior_disp, prior_cases, prev_as_of, rerun = _prior_state(
            spark, base_run_id, cycle_no, ledger
        )
        carry = None
        if prior_disp is not None:
            # Customers only, and only those still customers: an entity that
            # left the monitored population has its alerts out of scope now.
            still = entities.where(col("is_customer") == lit(True)).select("entity_id").distinct()
            carry = prior_disp.where(
                col("is_customer") & (col("disposition") != lit(DISP_OVER_CAPACITY))
            ).join(still, "entity_id", "left_semi")
            prior_disp = prior_disp.join(still, "entity_id", "left_semi")

        # Stage 6-8: triage, cases, SAR decisions.
        alerts = spark.table(f"{CATALOG}.{GOLD_ALERTS}").where(col("run_id") == lit(run_id))
        inputs = build_alert_inputs(spark, alerts, entities, manifest, params, carry).persist()
        held.append(inputs)
        disp_sim, cases_sim, tagged = simulate(
            spark, inputs, carry, params, as_of, prev_as_of, cycle_no
        )
        held.append(tagged)
        run_cols = [
            lit(as_of).cast("date").alias("as_of_date"),
            lit(cycle_no).cast("int").alias("cycle"),
            lit(base_run_id).alias("base_run_id"),
            lit(run_id).alias("run_id"),
            current_timestamp().alias("computed_ts"),
        ]
        declared = list(params.get("counterparty_scenarios") or ())
        disp_cols = [n for n, _ in ddl_columns(DDL_DISPOSITIONS)][:-5]
        sim_rows = (
            disp_sim.withColumn("alert_ts", timestamp_micros(col("alert_ts")))
            .withColumn("is_customer", lit(True))
            .withColumn(
                "declared_counterparty",
                col("rule_id").isin(declared) if declared else lit(False),
            )
        )
        # Alerts the replay does not work: on a non-customer (outside the
        # monitored population) or over the per-customer cap.
        other = inputs.where(~col("is_customer") | col("over_capacity")).select(
            "alert_id",
            "alert_key",
            "rule_id",
            "entity_id",
            "is_customer",
            "declared_counterparty",
            "crr_tier",
            "scenario_weight",
            "priority_score",
            "triage_priority",
            "alert_ts",
            "content_hash",
            lit(None).cast("int").alias("first_seen_cycle"),
            lit(None).cast("date").alias("first_seen_as_of"),
            lit(True).alias("in_current_detection"),
            "generated_date",
            lit(None).cast("date").alias("l1_decision_date"),
            _when_customer(lit(DISP_OVER_CAPACITY), lit(DISP_OUT_OF_SCOPE)).alias("disposition"),
            lit("closed").alias("queue_status"),
            lit(None).cast("string").alias("case_id"),
            col("generated_date").alias("decision_date"),
            lit(0).alias("aging_days"),
            lit(False).alias("sla_breached"),
            "simulated_truth",
            lit(None).cast("boolean").alias("analyst_correct"),
            lit(False).alias("qa_sampled"),
            lit(None).cast("string").alias("qa_disposition"),
            lit(None).cast("boolean").alias("qa_disagrees"),
        )
        disp = sim_rows.select(*disp_cols).unionByName(other.select(*disp_cols))
        disp.select(*disp_cols, *run_cols).writeTo(f"{CATALOG}.{GOLD_DISPOSITIONS}").overwrite(
            lit(True)
        )
        activity = case_activity(txns, cases_sim)
        case_cols = [n for n, _ in ddl_columns(DDL_CASES)][:-5]
        cases = cases_sim.join(activity, "case_id", "left").withColumn(
            "activity_txn_count", _coalesce_long("activity_txn_count")
        )
        cases.select(*case_cols, *run_cols).writeTo(f"{CATALOG}.{GOLD_CASES}").overwrite(lit(True))

        # Scenario coverage matrix.
        try:
            status_rows = [
                r.asDict()
                for r in spark.table(f"{CATALOG}.{GOLD_STATUS}")
                .where(col("run_id") == lit(run_id))
                .collect()
            ]
        except Exception as e:  # noqa: BLE001
            log(f"[tm] detection_status not readable: {one_line(e)}")
            status_rows = []
        cov = coverage_rows(spark, inputs, status_rows, manifest, rule_targets)
        spark.createDataFrame(
            cov,
            "typology STRING, rule_id STRING, coverage STRING, rule_status STRING, "
            "alert_count BIGINT, customer_alert_count BIGINT, planted_instances BIGINT",
        ).select(
            "*", lit(run_id).alias("run_id"), current_timestamp().alias("computed_ts")
        ).writeTo(f"{CATALOG}.{GOLD_COVERAGE}").overwrite(lit(True))

        # Read the written tables back once; the funnel rows complete the
        # cycle ledger, and the invariants read the ledger as written.
        counts = read_back(spark, run_id, as_of, prior_disp, prior_cases, prev_as_of, rerun)
        recon_rows = recon_rows + [
            ("funnel", "alerts", "alerts", counts["customer_alerts"], None),
            ("funnel", "alerts_out_of_scope", "alerts", counts["noncustomer_alerts"], None),
            (
                "funnel",
                "alerts_noncustomer_undeclared",
                "alerts",
                counts["noncustomer_undeclared"],
                None,
            ),
            ("funnel", "escalated", "alerts", counts["escalated"], None),
            ("funnel", "cases", "cases", counts["alert_cases"], None),
            ("funnel", "continuing_review_cases", "cases", counts["review_cases"], None),
            ("funnel", "sars", "sars", counts["alert_sars"], None),
            ("funnel", "continuing_sars", "sars", counts["review_sars"], None),
        ]
        _write_recon(spark, recon_rows, base_run_id, cycle_no, cycle_run_id, as_of)
        rec = {
            (r["section"], r["item"]): r["item_count"]
            for r in spark.table(f"{CATALOG}.{GOLD_RECON}")
            .where((col("run_id") == lit(base_run_id)) & (col("cycle") == lit(cycle_no)))
            .collect()
        }
        src = rec.get(("completeness", "source"))
        counts.update(
            {
                "negative_items": sorted(
                    f"{s}.{i}={v}" for (s, i), v in rec.items() if v is not None and v < 0
                ),
                "source": None if src is None else int(src),
                "customers": int(rec.get(("completeness", "customers")) or 0),
                "silver": int(rec.get(("completeness", "silver")) or 0),
                "monitored": int(rec.get(("completeness", "monitored")) or 0),
                "excluded": int(rec.get(("completeness", "excluded")) or 0),
            }
        )
        invariants = evaluate_invariants(counts)
        summary = ops_summary(as_of, params, recon_rows, counts)
    except Exception as e:  # noqa: BLE001 -- reported through the gate
        err = one_line(f"{type(e).__name__}: {e}", limit=400)
        _status("not_run", cycle_no, f"error: {err}")
        return [("workflow", "not_run", f"error: {err}")]
    finally:
        for df in held:
            try:
                df.unpersist()
            except Exception:  # noqa: BLE001
                pass

    _status("ran", cycle_no, "ok")
    for name, status, detail in invariants:
        log(f"[tm-invariant] {name}: status={status} cycle={cycle_no} detail={detail}")
    summary["cycle"] = cycle_no
    if tick is not None:
        summary["gold_refresh_tick"] = tick
    summary["elapsed_seconds"] = round(time.time() - started, 1)
    summary["invariants"] = {n: {"status": s, "detail": d} for n, s, d in invariants}
    log("[tm-ops] " + json.dumps(summary, sort_keys=True, default=str))
    return invariants


def _when_customer(yes, no):
    from pyspark.sql.functions import col, when

    return when(col("is_customer"), yes).otherwise(no)


def _coalesce_long(name):
    from pyspark.sql.functions import coalesce, col, lit

    return coalesce(col(name), lit(0)).cast("bigint")
